### ISSUE TITLE
Determine Responsive Breakpoints

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8io/fabric8-ux#1]
As a user, I want to be able to view the ALMighty UI on a multitude of devices. In order to do so, the interface must scale properly, depending on the size of the device's viewport.

A base determination for responsive sets needs to be determined in order for the initial UI release to be usable on more than the desktop platform.

Existing JIRA Story: https://patternfly.atlassian.net/browse/RHUAP-264

---

These are the default media queries in PatternFly: 

```
/* Extra small devices (phones, less than 768px) */
/* No media query since this is the default in Bootstrap */

/* Small devices (tablets, 768px and up) */
@media (min-width: @screen-sm-min) { ... }

/* Medium devices (desktops, 992px and up) */
@media (min-width: @screen-md-min) { ... }

/* Large devices (large desktops, 1200px and up) */
@media (min-width: @screen-lg-min) { ... }
```

**Comment by Mgranfie** [comment]
Hey be great to get in a habit of using the Story template of... As a <type of user>, I want <some goal> so that <some reason>. This will help us all understand each others stories... thanks!

**Comment by mindreeper2420** [comment]
@michaelkleinhenz would you be able to start with the default PatternFly/Bootstrap media queries, and expand from there at a later point?
```

/* Extra small devices (phones, less than 768px) */
/* No media query since this is the default in Bootstrap */

/* Small devices (tablets, 768px and up) */
@media (min-width: @screen-sm-min) { ... }

/* Medium devices (desktops, 992px and up) */
@media (min-width: @screen-md-min) { ... }

/* Large devices (large desktops, 1200px and up) */
@media (min-width: @screen-lg-min) { ... }
```

**Comment by michaelkleinhenz** [comment]
@mindreeper2420 Yes, that's exactly the info I was looking for. Thanks!
