### ISSUE TITLE
DISCOVERY: Areas [5]

### ISSUE THREAD

**Issue by Essjaysee** [fabric8io/fabric8-ux#101]
Work with Todd and Pete to gain an understanding of Areas and their role in the product.

Requirements:

- Understand what an area is
- Understand what can and can't be done with an area
- Have questions answered

AC:

- Todd/Pete have answered questions needed for design to have an understandable list of requirements.
- it is clear which users will utilize this feature and how it impacts other users.
- Questions have been answered.

(Originally RHUAP-584)

**Comment by mindreeper2420** [comment]
First iteration of Areas - future iterations to occur.

![areas](https://cloud.githubusercontent.com/assets/4032718/21998800/e35e6846-dc04-11e6-9ccf-84cc1c1c4e9e.png)

**Comment by mindreeper2420** [comment]
Second Iteration of Areas

![areas](https://cloud.githubusercontent.com/assets/4032718/22027781/eb593b68-dca2-11e6-8b31-ccf82e79aaa2.png)

**Comment by mindreeper2420** [comment]
Final iteration of Areas
![areas](https://cloud.githubusercontent.com/assets/4032718/22036039/11be67b6-dcc0-11e6-8518-ff693035c0fe.png)

**Comment by michaelvirgil** [comment]
@mindreeper2420 Regarding the comment that "there can be an infinite number of backlogs." Since each space has a single backlog - there can be only one - the work items that are in view are based on a query... do you mean that there is an infinite number of views into the backlog? Context is effectively a query and sets scope.

**Comment by mindreeper2420** [comment]
@michaelvirgil Perhaps it should be that there are an infinite number of queries that can render an infinite number of Backlog views? The breakout is as you said - there are an infinite number of views into a backlog, depending on the query that is selected (or created).

**Comment by Mgranfie** [comment]
I took this as there can be an infinite number of views on the backlog as
well Adam... Meaning that any number of queries can be crafted for the view.

Not sure if there is a limit to spaces and areas, I read in TFS there is a
limit and I am sure we have one.... this would limit the number of physical
list/tree components representing the backlog. As far as a limit to the
number of queries stored and what that is based on I don't know.....

**Comment by mindreeper2420** [comment]
General Information from Todd:

- Both Areas and Iterations are hierarchies/trees of data. Each node has a name. Areas do not really have any additional info. Iterations have start & end date, plus UXD has recommended Description. 

- Areas (and Iterations) are configured through an Editor of some kind. The location of this editor is unknown (UXD decision), but should be similar (if not the same) as the Iteration editor. 

> Assume that these editors can fill the entire blank space inside of the UI (e.g. below the top navigation and above the footer). We'll eventually find the right tabs on which to place them.

> I'd like to recommend that the default area has the same name as the name of the Space, rather than "/". I know that's the opposite of what I've told some of you in the past. :) The UX feedback that drove this change was wise. 
> Similarly, the default root of Iterations will also be the same name as the Space. i.e., in space Foo, there is a default area 'Foo' and a default iteration 'Foo'. Neither of these may be renamed or deleted. All others are descendants of them. (E.g., if the user adds Sprint 1 and Sprint 2, those are both children of iteration Foo. So Foo/Sprint 1 and Foo/Sprint 2. Of course, Sprint 1 and Sprint 2 may also have their own children, etc.)

**Comment by mindreeper2420** [comment]
![areas](https://cloud.githubusercontent.com/assets/4032718/22070561/7917dd98-dd6a-11e6-92f3-1bb3c25f2cd2.png)

**Comment by aslakknutsen** [comment]
"Iterations are tied to Spaces(which are tied to areas), so they are team agnostic"?

That kinda implies an Area is above a Space?

**Comment by ldimaggi** [comment]
Questions/Comments on the diagram:



Team Hierarchy
  * Teams contain 1..n people (each person can be on 1..n teams) and provide user perms
    * Each team can be associated with 1..n areas

Organization Hierarchy
  * Spaces (formerly called "projects"), each space contains one backlog
    * Areas - hierachical, expressed in paths
    * Iterations (can also have child iterations)

Planning Hierarchy
  * Epics
    * Stories
      * Tasks

Execution Hierarchy
  * Release (can also have child releases)
    * Iterations (can also have child iterations)
      * Sprints


Open Questions:
* Can teams be hierarchical?
* Are releases a type of iteration?

Thx!

**Comment by kwk** [comment]
> That kinda implies an Area is above a Space?

Good question.

**Comment by mindreeper2420** [comment]
@kwk @aslakknutsen That wording needs to be fixed. Areas should not be above Spaces. Good catch.

@ldimaggi Hierarchical Teams have not been discussed, but I don't see why they couldn't be - also not sure why they would be? I guess if you wanted to share permissions, but have smaller subsets of Teams. Something that will have to be brought back to the table for further discussion.

I would definitely say that Releases are a type of Iteration.
