### ISSUE TITLE
WIREFRAMES, VISUALS: Work item - when created [3]

### ISSUE THREAD

**Issue by Essjaysee** [fabric8io/fabric8-ux#107]
As a user of the ALM system, I want to know when the WorkItem was created, so that I know how long the WI has been in existence.

Acceptance Criteria:
1. User should be able to locate when the WI was created.
2. The time created should be localizable
3. The text is static text.

Questions:
1. Does the when created change with modification of the work item or does this just get captured in the history and the original created date always remains visible? 
2. What does the user need here, an exact date or time ago?
3. Does the user need to see a "Last Modified" when?
3. Will this information also be captured in the WI History?
4. The place in layout needs to be determined, as well as other visual elements, size and color of the font.

(Originally RHUAP-569)

**Comment by bdellasc** [comment]
Visual Specs and placement of this information is [here](https://redhat.invisionapp.com/share/6PAFLW2AJ).

Final wording is [here](https://docs.google.com/document/d/1DuBgTaX_U_OGcmzwUHVLpkuRhGsVCVFpBX6bgKm2d4s/edit)
