### ISSUE TITLE
Create + Edit Effort Estimation of Work Items

### ISSUE THREAD

**Issue by Mgranfie** [fabric8io/fabric8-ux#109]
Design in where to enter and how to edit, and display within the layout, the estimation of work on a work item.

Acceptance Criteria:
(Some of this is still being worked out)

* User is able to enter an a value (alpha and or alpha-numeric is still being determined) to estimate the work amount estimated for that work item.
* User is able to edit the value on the work item.
* The unit of measure on the time is obvious to the user.
* The effort estimate field may not be empty, meaning the default is 0 or none, depending on if it is alpha or numeric.
* Changes to the estimate should be captured in the History and Activity UI's.

See dev story:
https://github.com/fabric8io/fabric8-planner/issues/662

**Comment by mindreeper2420** [comment]
@Mgranfie If a Story or Draft of a Story, please add the appropriate label for planning purposes.
