### ISSUE TITLE
Create + Edit priority on a work item

### ISSUE THREAD

**Issue by Mgranfie** [fabric8io/fabric8-ux#110]
As a user, I want to see the priority value of a work item in the work item list view and on the work item, when the work item is open and assign and edit a priority on an open work item only.

** Need clarification on if this is create, or assign a priority to a WI**

Functional Acceptance Criteria

* A user can determine the priority type(not to be confused with the order in the backlog) by viewing the work item in the list.
* A user can assign and edit the priority type on an open work item.

See Related Dev Issues:

https://github.com/fabric8io/fabric8-planner/issues/661
https://github.com/fabric8io/fabric8-planner/issues/659

**Comment by mindreeper2420** [comment]
@Mgranfie If a Story or Draft of a Story, please add the appropriate label for planning purposes.
