### ISSUE TITLE
WIREFRAME: Behavior for resize of the current Planner page [13]

### ISSUE THREAD

**Issue by Mgranfie** [fabric8io/fabric8-ux#111]
Need to review what happens to this view when it is resized and how this will impact mobile.

Areas of Concern:
- List View
- Detail Panel
- Quick Add
- Iteration Panel
- New Iteration action
- Filter/Move action bar

VC:
1. A resize solution for desktop and mobile that meets the needs of the users', matches requirements of the product, and development is able to implement. This should take into consideration, any current behaviors + implementation.

**Comment by mindreeper2420** [comment]
@Mgranfie is this a Story or a Draft of a Story? There are individual labels for each, so that the Backlog and Issue list can be sorted correctly for Sprint Planning.

**Comment by mindreeper2420** [comment]
@Mgranfie @Essjaysee @bdellasc Here is the wireframe for the Planner on smaller screens (iPhone 6 to start): https://redhat.invisionapp.com/share/F6A55SUEJ. It is a bit rough right now, as I've first tried to make sure the everything is readable (thanks, Brian, for the help with sizing). I know that the Quick Add has been a big part from the beginning, but wow - it is kind of hard to work with on a touchscreen device, without taking up the entire screen.
