### ISSUE TITLE
WIREFRAMES: Order of Execution

### ISSUE THREAD

**Issue by nimishamukherjee** [fabric8io/fabric8-ux#119]
We have implemented the order of execution. Could you review and provide your feedback?
https://github.com/fabric8io/fabric8-planner/pull/609 has some discussions around order of execution

http://demo.almighty.io/

1. Drag and drop
- Click and drag a work item and drop it at it's new location
- The user can drag and scroll

2. Select a work item and move it
- Check-boxes are displayed for all the work items
- A user can move the work item after selecting a check box
- On selecting the check box, a Move drop down menu is displayed next to the Backlog text
- Move to Top will place the selected work item as the first item of the list
- Move to Bottom will place the selected work item as the last item of the loaded list
- As we are moving a single work item, only one work item can be checked at a time

3. Consider this scenario
- Work item A has been selected, it's detail pane is open.
- Select Work item B's check box, the Move menu is displayed
- Move Work Item B to it's new location
- UI behavior - Work Item A is highlighted and it's detail screen remain open. Work Item B moves up or down to it's new location.

**Comment by mindreeper2420** [comment]
Bugs have been filed against the UI for Ordering Items
- https://github.com/fabric8io/fabric8-planner/issues/683
- https://github.com/fabric8io/fabric8-planner/issues/684
- https://github.com/fabric8io/fabric8-planner/issues/685
- https://github.com/fabric8io/fabric8-planner/issues/686
- https://github.com/fabric8io/fabric8-planner/issues/687

The current UI does not follow the wireframes, and notes have been made accordingly.

Additionally, the Drag and Drop does not match the screens as given by UX. What screens were referenced when implementing that behavior? If the methods are to be used elsewhere, they need to be fixed first.

**Comment by mindreeper2420** [comment]
Additionally, these should all be reviewed with the @fabric8io/uxd team before pushing the code to master, given the continuous deployment cycle. This will avoid the need to file bugs for items that should have been caught before the merge.

**Comment by nimishamukherjee** [comment]
Thanks @mindreeper2420. Going forward we will share screenshots and videos of the PR before merging.

**Comment by mindreeper2420** [comment]
@nimishamukherjee sounds good. The videos that have been posted in the past worked out very well.
