### ISSUE TITLE
FOLLOW THROUGH: Fix filters UI [2]

### ISSUE THREAD

**Issue by Mgranfie** [fabric8io/fabric8-ux#121]
The UI for the filters is needs to be brought in line with PatternFly and is currently residing in two areas within the layout of the Planner Page.

VC's

* the filter follows the PatternFly design
* the filter takes into consideration the layout of other elements on that area of the page.

**Comment by mindreeper2420** [comment]
The pre-defined filters wireframe has been updated to properly reflect PatternFly's UI. The link can be found [here](https://redhat.invisionapp.com/share/T79EF22F9#/208756097_Fixed_Filter_-_000). I will create an Enhancement request in the Fabric8-Planner area for updating the UI with this new wireframe.
