### ISSUE TITLE
WIREFRAMES: Areas

### ISSUE THREAD

**Issue by Mgranfie** [fabric8io/fabric8-ux#129]
As a designer of the Areas feature, I need to create a set of wireframes that provide a solution that represents what the area object is, how and where to create and edit it, so that a user understands what this is and how to access it.

VC's

1. Design area item and attributes to be represented in it.
2. Design/reuse work item edit solutions.
3. Determine and design in access points and location or environment for representation of access to Areas.
3b. Communicate with other designers on touch points where areas are realized in the UI.
4. Post to InVision and share the link.
5. Review with dev, UX, and stakeholders. (may need to be separate story)

InVision Link: https://redhat.invisionapp.com/share/MBA35RRXU

Discovery Story: #101

**Comment by mindreeper2420** [comment]
Linking Discovery story: #101

**Comment by mindreeper2420** [comment]
@Mgranfie @Essjaysee @deernano so far, I have Areas surfacing in the List View, Board View, Project Settings, Detail Panel, Iteration Panel, and in Area and Iteration Editor/Creator. Are there any other places that I'm missing?

**Comment by Essjaysee** [comment]
In both the quick add and the long-form add for work items, the context is assumed from where you invoke the creation, right?

**Comment by Mgranfie** [comment]
How would the area show in the iteration? this is in context too?...

**Comment by mindreeper2420** [comment]
@Essjaysee yes, the context is assumed. For Summit, there is only the single Area, so that is a simple one. Long-term, I'm thinking that the user will be able to change the Area that they wish to have the WI end up in while entering information into the long-form Add WI.

@Mgranfie If I understand the question correctly, the Area would not show in the Iteration, as Iterations can only be in Areas, not Areas inside of Iterations. As for showing what Area your Iteration is in, the wireframe has that as a new line item in the Detail View, as well as a header in the Iteration Panel.

**Comment by Mgranfie** [comment]
Ok thanks Adam, just checking as you mentioned that you had Areas surfacing
in the Iterations pane and wanted to make sure I had not missed
something....

**Comment by mindreeper2420** [comment]
@Mgranfie The name of the Area surfaces in the Iterations Panel, allowing the user to see what Area they are actually in (which is something we've had issues figuring out in reference materials). The InVision link better demonstrates my thought on this :-)

@Essjaysee @Mgranfie After some additional thought, here is a breakdown of how I see Areas coming into play, both now and long term.

Now:
- List View
- Board View
- Project Settings
- Work Item Detail Panel
- Iteration Panel
- Iteration / Area Editor

Long Term (when multiple Areas come into play):
- Filter By 'Fabric8/Area 2'
- Sort By 'Fabric8/Area 2 w/Open Items'
- Move to 'Fabric8/Area 3'
- Add to 'Fabric8/Area 2' (when creating a Work Item with Detail Panel)
- Team Permissions (assign a Team to a specific Area or multiple Areas)

**Comment by Mgranfie** [comment]
Thanks for the information Adam.

We can work out the placement of the area name in the visual phase, no
problem.

I am still getting confused as to what the iteration panel, you are
referring to, is?

This is a helpful enumeration of the scenarios to consider moving forward
and designing with these in mind, thanks.

**Comment by mindreeper2420** [comment]
@Mgranfie the Iteration Panel is the panel on the left side that Sj worked on. Just seemed a half-decent name for it :-)

**Comment by Mgranfie** [comment]
Just that it contains the back log and epics too... hmmm what generic names
for things are left ; )
