### ISSUE TITLE
VISUALS: Comments UI [8]

### ISSUE THREAD

**Issue by Mgranfie** [fabric8io/fabric8-ux#131]
As a visual designer on fabric8, I want to apply visual standards for the interaction, feedback and layout of this UI, using PatternFly, where I can and specifying anything additional, that is not in PatternFly.

VC's
1. All interactions, visual states, conditions of feedback, to support the UI Wireframes have been specified for visuals.
2. The layout and dimensions have been provided.
3. @bdellasc has verified the visuals as accurate and complete.

Related stories:

 https://github.com/fabric8io/fabric8-ux/issues/65

**Comment by bdellasc** [comment]
Basic design work is done. Next step will be the [specifications story](https://github.com/fabric8io/fabric8-ux/issues/192).
