### ISSUE TITLE
VISUALS: Review Planner View Filter Panel

### ISSUE THREAD

**Issue by bdellasc** [fabric8io/fabric8-ux#132]
Verification Conditions:
- Review Screen captures and questions from development - @nimishamukherjee, please ask the team to add comments to this story
- Understand what the misalignment (sizing & mobile-friendly issues) is between the PatternFly styling and what has been designed
- Give guidance to development on resolving the conflicts between the intended design, PatternFly and the implementation of the filter panel

**Comment by SMahil** [comment]
@bdellasc For filter bar: patternfly design falls as per first two screenshots.

<img width="978" alt="screen shot 2017-01-19 at 10 21 20 pm" src="https://cloud.githubusercontent.com/assets/10396359/22116245/ea13087a-de95-11e6-97a0-ee0c19c827a4.png">
<img width="942" alt="screen shot 2017-01-19 at 10 21 39 pm" src="https://cloud.githubusercontent.com/assets/10396359/22116257/f11fbdf2-de95-11e6-81cd-3de7c85c6d49.png">


we left with tap area of 24*24 but as per the visual design we have to keep it 40*40

<img width="982" alt="screen shot 2017-01-19 at 10 22 22 pm" src="https://cloud.githubusercontent.com/assets/10396359/22116296/11367fb8-de96-11e6-9518-4b0a14ec8f1f.png">

**Comment by bdellasc** [comment]
Will add this to a future sprint once filter design that Catherine posted is implemented.
