### ISSUE TITLE
VISUALS: Planner Work List w/hierarchy

### ISSUE THREAD

**Issue by bdellasc** [fabric8io/fabric8-ux#133]
Verification Conditions:
- Review wireframes
- Understand the needs from a visual standpoint
- Design out the re-imagined list

**Comment by catrobson** [comment]
Wireframes for this story can be found here:  https://redhat.invisionapp.com/d/main#/projects/prototypes/10109165

**Comment by bdellasc** [comment]
@sunilmalagi - there was a part in @catrobson 's design that I missed and didn't point it out to you. I'm just going to work on that part (it appears in the details view), and I'll base it on the work you've done so far on the Comments and Relationship Links.

**Comment by bdellasc** [comment]
The plan is to sit with Adam @ Dana to get these pieces implemented as designed instead of spec'ing them.
