### ISSUE TITLE
VISUALS (SPECS): Planner Work Board

### ISSUE THREAD

**Issue by bdellasc** [fabric8io/fabric8-ux#136]
Verification Requirements:
Refer to previous visual story: [Visuals: Planner Work Board](https://github.com/fabric8io/fabric8-ux/issues/135), then:

- Add specifications to previous visuals work
- Post new visual specs to InVision, review with UX team members
- Link to InVision prototypes from this story
- Tag story as "Ready for Development"

**Comment by bdellasc** [comment]
Verification Conditions:
- Add specifications work completed in Visuals step
- Post specs to InVision
- Tag story as "Ready for Development"

**Comment by deernano** [comment]
Here is the invision link of the plan work board visual design
https://redhat.invisionapp.com/share/URAY3RS7Y#/224687427_Boardview-1

**Comment by catrobson** [comment]
Specs can be found here:  https://redhat.invisionapp.com/share/GWBAMBMSC

**Comment by deernano** [comment]
Here is the Invision link of the planner work board (SPECS) design
https://redhat.invisionapp.com/share/GWBAMBMSC#/228695361_Boardview-1

**Comment by bdellasc** [comment]
@jryhanyc looked through it, gave feedback
