### ISSUE TITLE
which element would sit on top of which?

### ISSUE THREAD

**Issue by vikram-raj** [fabric8io/fabric8-ux#137]
Please refer to this issue https://github.com/fabric8io/fabric8-planner/issues/810.

**Comment by mindreeper2420** [comment]
@vikram-raj These were asked in https://github.com/fabric8io/fabric8-planner/pull/812, but I wanted to post the questions here as well. Feel free to answer them in the Fabric8-Planner area.

Questions:

- why does the panel have a z-index of 100? Why so high? Also, I was unable to find a z-index for any other element - modal, navigation, or anything else.
- Do other elements already have z-indexes?
- Is Bootstrap / PatternFly being used to control the layering, as it should? Those frameworks cover layering for modals, slideouts, and other aspects. Custom code should not be there for that. @michaelkleinhenz, @michaelvirgil - how much of Bootstrap/PatternFly is being used at this point?

We will most likely not be able to give you a z-index for every single element - that is what the embedded frameworks are for. The CSS for each framework will properly handle the button layering, modal layering, etc.
