### ISSUE TITLE
WIREFRAMES - Iterations: Revisions to displaying date in the UI

### ISSUE THREAD

**Issue by Mgranfie** [fabric8io/fabric8-ux#138]
As a user of the product I want to be able to have the option to assign a date to an iteration, at the time I define/create the iteration, so I don't have to reopen the iteration to assign it a date.

VC's

* Update  the wireframes to allow for, optionally defining a date and description, for an iteration that is newly being created. 
* Review with development

**Comment by Essjaysee** [comment]
https://redhat.invisionapp.com/share/KA9CAYL7M
