### ISSUE TITLE
In Development: Interaction Design Backlog Planning List View

### ISSUE THREAD

**Issue by Mgranfie** [fabric8io/fabric8-ux#14]
Persona: PM/PO

Aa a PM or PO using ALM, I want to be able to create and view, a list of work items, so that I can create work for the team, see the status of the work item.

Verification Criteria:
User can created, edit and remove a work item, immediately upon logging in, with no questions.

InVision Designs:
UI: https://redhat.invisionapp.com/share/VW8E0F2DY
Menus: https://redhat.invisionapp.com/share/WB8FNVPYE

In JIRA:
https://patternfly.atlassian.net/browse/RHUAP-238

**Comment by mindreeper2420** [comment]
is there a Persona that can be attached to this?

**Comment by mindreeper2420** [comment]
@Mgranfie does the 'In Development' in the title mean that it is currently being developed by almighty-ui, or is it something to be developed?
