### ISSUE TITLE
WIREFRAMES: Iterations - Verbiage

### ISSUE THREAD

**Issue by Mgranfie** [fabric8io/fabric8-ux#140]
Update the Assign vs. Attach verbiage in the Iterations UI for consistency.

**Comment by Essjaysee** [comment]
https://redhat.invisionapp.com/share/KA9CAYL7M

**Comment by Mgranfie** [comment]
If this changes the verbiage on the menu, please update the common menu
component in the InVision ALM space for accuracy.
