### ISSUE TITLE
FOLLOW UP: Save a work item interactions

### ISSUE THREAD

**Issue by Mgranfie** [fabric8io/fabric8-ux#142]
As a user there are work flows for when I am editing data in a work item and I do any of the following actions:

1. Click on another work item in the list
2. Click in any other area of the UI, outside of the work item
3. Click on another data element in the UI of the work item, while editing data on the open work item.
4. Close the work item, while editing data on the open work item.

Actions to consider while defining or editing:
1. Name
2. Assigning a user
3. Changing Owner
4. Status
5. Description
6. Epic
7. Work Item Link
8. Close

VC's

1. The conditions under which clicking away from the create or edit action of the meta data has been defined and confirmed by dev.
2. The data persist possibilities have been reviewed with dev and are understood.
3. Wireframes have been created to reflect solutions for each of these conditions.
4. Solutions for each of these conditions has been established with Dev.

**Comment by Mgranfie** [comment]
Previous email discussion... include here for background.

My feedback and questions in line below. Good catch on these scenarios where we click away mid- edit or create on an open work item.
@fabric8io/uxd could you please let us know the experience in the following scenarios:
Scenario 1

Filter by "Assign to me" (mg)should this be "assigned" to me?
Click on any of the work item and open it's detailed view
Un-assign the work item
The work item list needs to get updated. What happens to the detailed view - do we need to close it?
(mg) Adam may want to contribute here... my thinking is that the user clicks on the Unassign command. The list closes and the text next the the field changes to Unassigned and the user clicks on the checkmark or x to accept or cancel the change. 
Scenario 2

On the list view, open a work item detailed view, which has not been "assigned to me"
While the detail view is open, click on Filter > "Assign to me"(mg)should this be "assigned" to me?
The filtered list shows up
Question - what happens to the detailed view? Does it remain open? This work item will not show up in the filtered list as it has not been "Assigned to me".
(mg) to me it sounds like if you invoke a filter, meaning change the iteration selected on the left or a filter at the top or place focus in the search field, the detailed work item should close, under those circumstances. 

Questions around this behavior:

1.  If a change is being made on the WI and has not been committed, one way or the other, we have to flag that with an inline error or dialog, depending on the interaction, and not close the detailed WI.

2. In situations where it might not matter, ie: assigning a WIL, I have searched  and selected a WI link but not linked it yet, would this data persist in the field, while the browser is in session, so that when a user navigates back the data will be there? If we can't do this, we should throw an error. on the linking part of the UI.

3.  Same consideration on comments... 
a. When entering a comment and the user navigates away from the detailed open WI. Do we persist the entry, can we, per browser session?
b. Editing a comment would throw an in line error and prevent the WI from being closed.

4. Attaching an iteration (SJ jump in here)

I think that is all we have on the WI for now. If we all agree on these rules, we can continue to take the solution into consideration, as we build out the WI with more data.

If you can let us know which solutions might be possible and if this makes sense, we can refine from here.

Thanks,
Monica


Nimisha Mukherjee
Jan 25 (1 day ago)

to Sudipta, Michael, Michael, Vikram, Sukhvir, Soumya, me, Adam, Sarahjane 
Hi Monica,

Good points! I think we need to come up with the overall save behaviour be it for work items or iterations. Please have a look at my responses.

(mg) Adam may want to contribute here... my thinking is that the user clicks on the Unassign command. The list closes and the text next the the field changes to Unassigned and the user clicks on the checkmark or x to accept or cancel the change. 
We really do not have a "commit the change" mechanism on the work item's detail page. There is no way to revert to the previous set of values.

(mg) to me it sounds like if you invoke a filter, meaning change the iteration selected on the left or a filter at the top or place focus in the search field, the detailed work item should close, under those circumstances. 
Agreed.


1.  If a change is being made on the WI and has not been committed, one way or the other, we have to flag that with an inline error or dialog, depending on the interaction, and not close the detailed WI.
Current Save Behaviour varies from field to field:
Title, description, and comments - these are text fields and get saved when user hits enter
State (new, open, in progress, etc) - this is a drop down and gets saved when a selection is made
Assignee - this is a drop down and gets saved when a selection is made
Iterations - this would behave in a manner similar to the state and assignee drop downs.
Links - user has to select a link and click on the link button
We really do not have a "commit the change" mechanism on the work item's detail page. There is no way to revert to the previous set of values.

**Comment by Essjaysee** [comment]
Another workflow: changing association for or associating with an iteration

**Comment by Mgranfie** [comment]
@mindreeper2420 this was related to the Save story you were working on. Can you verify if all of these questions have been answered and if so close this one out?.. thanks!!
