### ISSUE TITLE
Wireframes: Workspaces Landing Page (Che)

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8io/fabric8-ux#145]
As a user, I want to be able to manage my Che environment from within the Developer Platform. I should be able to manage the following:
- Stop a Workspace
- Start a Workspace
- Open a Workspace (brings me into a loaded Che environment)

**Comment by mindreeper2420** [comment]
Iterate off of this screen:
<img width="1858" alt="screen shot 2017-02-06 at 9 26 53 am" src="https://cloud.githubusercontent.com/assets/4032718/22650744/880e3606-ec4e-11e6-8bf3-8014de1ebd1e.png">

**Comment by mindreeper2420** [comment]
Wireframe for this Issue can be found here: [ALM_Workspaces_DT](https://redhat.invisionapp.com/share/GUABZY4PQ)

**Comment by mindreeper2420** [comment]
@joshuawilson this is Ready for Development - I believe it is a Platform piece?

**Comment by joshuawilson** [comment]
I thought Workspaces was dead? @aslakknutsen did you hear that?

**Comment by aslakknutsen** [comment]
It is. The flow is the same from codebases as from doit: https://redhat.invisionapp.com/share/5UAH0I2BE#/screens/221885524

The way it's designed now is:

When you click 'edit/doit', backend will check with che-starter if there are any available workspaces for the given repo that belongs to the user. If there are you get a choice to either; continue using one of them or create a new one.
