### ISSUE TITLE
UX for the work item list filtered by type.

### ISSUE THREAD

**Issue by nimishamukherjee** [fabric8io/fabric8-ux#147]
Issue - Filtered List: by Work Item Type (https://github.com/fabric8io/fabric8-planner/issues/658)

This issue is for the listing part only. Do we need any visual indicator, apart from the side bar, that the list of work items have been filtered by a work item type?

Please note point 3 in user story 658:
The work item type filter may or may not stack with the current display context ("Backlog" or "Iteration X"). The decision is on UX how this work.

**Comment by Mgranfie** [comment]
This was replaced with story https://github.com/fabric8io/fabric8-ux/issues/158
