### ISSUE TITLE
WIREFRAMES: Iterations - Show hierarchy as path

### ISSUE THREAD

**Issue by Mgranfie** [fabric8io/fabric8-ux#151]
To display iterations with a hierarchy in the left pane, a static path will be displayed.

VC's
* Truncation and localization factors are considered...
* The most important portion of the path is determined, the first or last part of the path should display?
* An overflow story to display the paths (ie: a hover tooltip or something of the sort) is provided, for the left pane.
* Rejigger the UI for assigning with a path on the work item.
* Overflow scrolling of the left pane provided.

Related to:

https://github.com/fabric8io/fabric8-planner/issues/909

**Comment by Essjaysee** [comment]
Iteration path: https://redhat.invisionapp.com/share/4NAGI5EVE#/219918403_Iteration_Path
Very long iteration path: https://redhat.invisionapp.com/share/4NAGI5EVE#/219918404_Iteration_Path_Long

5px vertically between the iteration name and the path
15px vertically between the path and the date
Use #72767b for the text color
