### ISSUE TITLE
WIREFRAMES: WorkItems generated as bugs to connect to IDE

### ISSUE THREAD

**Issue by Mgranfie** [fabric8io/fabric8-ux#152]
Bayesian will generate work items, as Bugs, in the planner. These work items will have the capability to navigate from the WI to the code in Che with a single click on the Bug WI.

VC's

1. Bug generated by auto are somehow differentiated, so that a user can identify them specifically.
2. Meta data for this WI type needs to be identified.
3. It is a WIT Bug
4. A user can navigate from this bug to IDE.

**Comment by Essjaysee** [comment]
I asked if bugs from Bayesian should be differentiated, and it seemed the general feeling was no.

"The developers will be able to check if the needed metadata is available - we should not distinguish/enable by type, but by availably of the metadata..."

@michaelvirgil Please comment?

**Comment by michaelvirgil** [comment]
@Essjaysee @Mgranfie A user should not know if this is a Bayesian generated defect. The key point is that the code will be able to determine if a defect has the necessary metadata to launch Che in context. It's more of - enable the "Do-It" button (has the metadata) or not (does not have the metadata. User should just see that the button is enabled or not... any service that has the metadata and the Planner API can create a defect that can launch Che in context.

**Comment by Mgranfie** [comment]
So if I am a user and I want to find that bug that will let me launch into
the code, traditional means of just knowing which bug it is... is
sufficient?...
