### ISSUE TITLE
WIREFRAMES: Areas - Assign with hierarchy on the work item

### ISSUE THREAD

**Issue by Mgranfie** [fabric8io/fabric8-ux#153]
If we are going to reveal the full paths of the Areas, the mechanism of how to assign them, on the work item, needs to be updated to reflect this capability.

VC's
* Determine if this is necessary with team and stakeholders
* Update the method/mechanism with which to assign the area on the work item, to accommodate hierarchy.

Related:
https://github.com/fabric8io/fabric8-planner/issues/913
https://github.com/fabric8io/fabric8-planner/issues/914

**Comment by mindreeper2420** [comment]
@Mgranfie @catrobson does this meet the requirements https://redhat.invisionapp.com/share/XCA839ET9? I've updated the wireframe with hierarchy in the selection menu.

**Comment by catrobson** [comment]
+1 - looks good to me!
