### ISSUE TITLE
UX REVIEW: Consistency of the accept + cancel save UI

### ISSUE THREAD

**Issue by Mgranfie** [fabric8io/fabric8-ux#154]
The UI for the context based Save needs to be reviewed for consistency on the wireframes and communicated back to dev to align the implementation of the UI with the wireframes.

	- Check + compare for consistency in wireframes of accept and cancel layout, behavior and visual presentation
	- Provide Dev with designs + meet to review

**Comment by mindreeper2420** [comment]
@Mgranfie Is this the same as this item - #149 ?

**Comment by Mgranfie** [comment]
No this is the one where all the checks and x's are different. So finding
all the places where this paradigm is used and comparing to original
wireframes vs. the implementation...

**Comment by mindreeper2420** [comment]
@Mgranfie as I'm working on the error handling for the inputs and dropdowns, I'd like to sync up with you to make sure that my wireframes are consistent with the proper Save models.

**Comment by Mgranfie** [comment]
Ok, cool, if you want to grab some time on the calendar we can walk through
it. I am not going to get to reviewing these until tomorrow... so would
tomorrow or Thursday work for you?
