### ISSUE TITLE
VISUALS: Reorder (Drag/Drop) Work Items in List

### ISSUE THREAD

**Issue by bdellasc** [fabric8io/fabric8-ux#155]
We need to specify the states for drag/drop reordering of work items in the Planner List View

Verification Conditions:
- Refer to [InVision Wireframes](https://redhat.invisionapp.com/share/GEAD9C2M5)
- Read the 3 comments in the InVision Wireframes before starting
- Download [source file](https://drive.google.com/open?id=0BwL_r77doqY_b1hmVTliZFBDU3M)
- Create mockups representing the various states for dragging/dropping work items within the planner list view
- Post screens to InVision for UX team review

**Comment by catrobson** [comment]
Note the rules of Drag-and-Drop at this point for what we need to visualize.  Users can drop *above* and *below* but not on top of other list items.  We'll likely need:

* Visual designator for allowed drop location between other work items
* Visual designator of not allowed drop location (you won't be able to drop across parent work items, only those items of the same level)
* What does the row look like in the "hold" state where users are dragging it around the screen

**Comment by bdellasc** [comment]
With the exception of a minor comment, this story is done.
