### ISSUE TITLE
WIREFRAMES: FilterBar

### ISSUE THREAD

**Issue by Mgranfie** [fabric8io/fabric8-ux#158]
As a user I want to be able to filter the work items, in the list view and boards view, based on filtering criteria as set in the template.

This issue is for the listing part only. Do we need any visual indicator, apart from the side bar, that the list of work items have been filtered by a work item type?

Please note point 3 in user story 658:
The work item type filter may or may not stack with the current display context ("Backlog" or "Iteration X"). The decision is on UX how this work.

VC's
* Use any capabilities from the PF Filter possible
* Choose Filter Type
* Choose established filtering criteria, if possible. If not type ahead will suffice.

**Comment by catrobson** [comment]
FIlter bar wireframes updated and interaction reflected in Hierarchy wireframes:
https://redhat.invisionapp.com/share/YVA4PGYA3#/216508673_Hierarchy_1_Level

**Comment by catrobson** [comment]
Wireframes updated to hide other parts of the pages beyond the filter bars and posted to InVision:  https://redhat.invisionapp.com/share/56AH8F1XM
