### ISSUE TITLE
WIREFRAMES: Areas - Manage

### ISSUE THREAD

**Issue by Mgranfie** [fabric8io/fabric8-ux#160]
As a user I want to be able to create new Areas in the product, to organize work efforts.

VC's
* Understand what data is needed to create an Area
* Create wireframes to surface the creation of Areas
* Understand where this UI will surface and to whom
* Vet the final wireframes with dev and stakeholders

Follow-Ups:
* The Filter options will need to be updated to show the ability to select from Parent and Child Areas
* Quick Add for creating a Work Item needs to be updated to reflect the selected Area (either in the Platform or as a Filter)

Wireframe: [Create Areas](https://redhat.invisionapp.com/share/7XAIMZBBK#/219785395_Admin_Areas-Settings-Dashboard_001)

**Comment by mindreeper2420** [comment]
@Mgranfie @catrobson @pmuir Questions on Label creation:

* Does Label creation need to be governed in a central spot (such as its own page)?
* Can Labels be created ad-hoc (if the desired Label is not available, can they create it in the selection dropdown, or do they have to go to a specific spot)?
* In the case of creating a Label for Areas, do they need to stay true to the long-term goal of what an Area will be?
* Should users be able to apply a Label as a filter, thus narrowing down results in the Backlog list?
* Can a Work Item have multiple (or infinite) Labels attached to it?

**Comment by mindreeper2420** [comment]
@joshuawilson @pmuir @michaelkleinhenz @michaelvirgil please review the Create Areas [wireframe](https://redhat.invisionapp.com/share/7XAIMZBBK#/219785392_Admin_Areas-Settings-Areas_002), if available. I reworked the Settings/Admin section a bit, as well as included the process for viewing Areas, settings Child Areas and Creating/Deleting Areas. There are six screens with interactions on each. Thanks!

**Comment by mindreeper2420** [comment]
Updated to reflect changes as requested. I believe that this fits the requirements for the firs iteration. Pete has vetted the design/process and we've discussed the information that can be surfaced to the user. @Mgranfie @Essjaysee can you review to verify that this issue can be set as 'ready for dev' for the Platform team?

**Comment by Mgranfie** [comment]
Hey Adam,

I took a quick look at this and left some comments. I was not able to find
my way to Delete or setting for Child areas...

Can you point in the direction for exposing these parts of the UI?

Thanks,
Monica

**Comment by mindreeper2420** [comment]
@mgranfie for this version, according to comments in the wireframe, there will not be the option to delete an Area. Setting an Area as a child element after it has been created is also something that was noted as not for this version. An Area can be set as a child Area when in the new Area creation process.

**Comment by Mgranfie** [comment]
Cool thanks.. I was a little confused bc I could not find all of the flow ;
)

**Comment by mindreeper2420** [comment]
Closing as this iteration has been vetted by Pete and the Platform team. Follow-up items needed for filtering Areas and showing levels inside of a Work Item Detail Panel.
