### ISSUE TITLE
WIREFRAMES: Add Markdown UI and behaviors to the Description and Comments entry field

### ISSUE THREAD

**Issue by Mgranfie** [fabric8io/fabric8-ux#161]
As a user I may want to format the text in the description or comments field, for handling specs or code.

VC's
* Technical implementation, of the widget and capabilities of the MD to html control, are understood per development. See GitHub for inspiration.
* The MD widget has been designed into the description and comments field
* A preview mode may need to be included to view the markdown (verify the behavior)
* Interaction and behaviors of the MD control in these fields has been understood and captured.

InVision Wireframe: https://redhat.invisionapp.com/share/SJAGM39CT

Related Issues:
https://github.com/fabric8io/fabric8-planner/issues/835
https://github.com/fabric8io/fabric8-planner/pull/942

Visual Design: #163

**Comment by mindreeper2420** [comment]
Notes from Joshua:

- First version: User can write in Markdown (.md), but no toolbar for assistance. Text cannot be previewed. Only shown as Markdown once committed.
- Second Version: Preview tab for seeing your Markdown before commiting. 
- Third Version: Control bar available to users who do not know how to write in Markdown.

**Comment by Mgranfie** [comment]
Thanks Adam... great to nail down the progression of capabilities here.
Are there dates/releases associated with these versions?

**Comment by mindreeper2420** [comment]
@Mgranfie the First Version is for Summit - the other two are for after, though I do not know the timeframe behind them. The Third Version with the control bar (from what Joshua told me) will be a tough implementation.

**Comment by mindreeper2420** [comment]
Updated Detail Panel to show Markdown support (as dictated by https://github.com/dcurtis/markdown-mark):

![markdownsupport](https://cloud.githubusercontent.com/assets/4032718/22943261/e656fc08-f2ba-11e6-8a97-9b72949aa695.png)

**Comment by mindreeper2420** [comment]
Updated Comment box to show Markdown support (as dictated by https://github.com/dcurtis/markdown-mark):

**Default Comment Section**
![comments_open](https://cloud.githubusercontent.com/assets/4032718/22957593/505aa5e6-f2f7-11e6-8340-c3fb1812ae7c.png)

----

**Add a Comment**
![comments_open-edit](https://cloud.githubusercontent.com/assets/4032718/22957595/5c3b19fe-f2f7-11e6-9ee0-ff719a2e4fa5.png)

----

**New Comment**
![comments_open-updated](https://cloud.githubusercontent.com/assets/4032718/22957600/66fa2c7c-f2f7-11e6-8886-74a7fca3d8aa.png)
