### ISSUE TITLE
VISUALS: Update Description and Comment Fields w/Markdown

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8io/fabric8-ux#163]
As the platform will be able to support Markdown in the text boxes, we need to properly display that information to the user. A wireframe has been created with the proper wording and placement, but the overall visual queues have not been considered.

According to the Markdown formatting requirements, the following Icon and specifications should be utilized: https://github.com/dcurtis/markdown-mark

See screen 2 in this wireframe flow: https://redhat.invisionapp.com/share/SJAGM39CT

**Comment by bdellasc** [comment]
I'll look more into this to see what (if any) Visuals support is needed

**Comment by bdellasc** [comment]
@mindreeper2420 - I think what you've provided in the description links is sufficient for development to implement. If there's standards out there for this feature, we should just stick to it.
