### ISSUE TITLE
WIREFRAMES: User Home Page Not Logged in

### ISSUE THREAD

**Issue by Mgranfie** [fabric8io/fabric8-ux#188]
As a user of the Openshift.io product, when I am not logged in, I would like to be fully aware that I am not logged in, and understand how I can log in and what other options are available to me, at this time, so that I can make the best decision based on my needs.

**Logged Out Requirements (pp.openshift.io/public)**
This is not part of the application, it's a public facing page, that will communicate that the user is not logged in.
	- Will use static HTML/CSS for presentation only (will be separate story to create the HTML/CSS)
        - Opportunity to request access to the product Beta
           * Enter First/Last Name
           * Enter email
        - May show product updates, what's new, other marketing materials that need to be determined and presented here.
	- Needs to address "This page is down scenario."

VC's

* Wireframes created
* Wireframes posted to InVision
* Wireframes reviewed with stakeholders + development

**Comment by catrobson** [comment]
@Mgranfie can we have logged out and logged in as two different wireframe stories?  I think both of these are significant work items to do, and should be tracked separately since they might take different timeframes to complete.

**Comment by catrobson** [comment]
@mindreeper2420 I think we can call the wireframes complete and add some stories to reflect the development work?

**Comment by mindreeper2420** [comment]
@catrobson yes-this will be closed. I've added various stories to reflect code work, with the CODE label. I'll go through and add additional ones for pieces I may have missed.
