### ISSUE TITLE
DISCOVERY: Build report: User feedback on recommendations part 2

### ISSUE THREAD

**Issue by jryhanyc** [fabric8io/fabric8-ux#195]
Research other methods for getting user feedback within the build report UI. 

Specifically address:
- Feedback on recommendations

VC:
- Share with ALM team
- Share with product team

**Comment by catrobson** [comment]
@jryhanyc - I think we should probably close this issue and talk about this as a larger gathering input on .io story.  Ok if I close this?

**Comment by jryhanyc** [comment]
@catrobson makes sense to me

**Comment by catrobson** [comment]
Closing as this will be part of the Design Exchange program strategy - starting with https://github.com/fabric8io/fabric8-ux/issues/412
