### ISSUE TITLE
WIREFRAMES: Build report: user notification outside the report modal

### ISSUE THREAD

**Issue by jryhanyc** [fabric8io/fabric8-ux#197]
As a user, when I am working in another part of the UI, I want to be notified when the build report is complete and ready to view.

Need to address:
1. How is the user notified when working in another part of the UI?
2. How is the user notified when on the Pipeline screen?

Ideas: 
- Email notification
- Alert within ALM UI (can this be dismissed/ directly linked to report)

**Comment by catrobson** [comment]
@jryhanyc - I'd like to close this issue and resolve this through the Notification design process since this affects more than Bayesian.  Ok to close this?

**Comment by jryhanyc** [comment]
sounds good @catrobson

**Comment by catrobson** [comment]
Closing, as will be handled as part of https://github.com/fabric8io/fabric8-ux/issues/408
