### ISSUE TITLE
Show Global and Local Errors in UI

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8io/fabric8-ux#2]
Example of current known global errors:

backend is not reachable
Example of local errors:

required field not filled out
validation errors

Existing JIRA Story: https://patternfly.atlassian.net/browse/RHUAP-297

---

Previous conversation from the UI Issue (since removed): 

5 days ago:
Monica: Quick ?... are the errors all being stored in one resource file? This can be an easy way to track and edit them easily... anyone have any know on this?

---

2 days ago:
Michael Kleinhenz: @Mgranfie you mean the text of the errors? That's possibly a more global thing, because we might do this for all text in the application and in connection to i18n. But this is an ongoing discussion right now. On tech as well as product level. So, short answer: we don't know yet. But assume yes for now.

---

Link to almighty-ui issue: https://github.com/almighty/almighty-ui/issues/72

**Comment by Mgranfie** [comment]
@mindreeper2420 Can you clarify this story... I want to make sure I am following. Is this story a task to create patterns for the errors or a reference to the list the dev has as a repository that we can then watch and edit as necessary?

**Comment by mindreeper2420** [comment]
also to investigate: error for when a user has no internet connection (specific to the mobile use cases)

**Comment by mindreeper2420** [comment]
@Mgranfie this is a task to create generic patterns for errors. My assumption is that they will be based off of PatternFly, but the backend apis might dictate that additional error patterns will need to be determined.

**Comment by michaelkleinhenz** [comment]
Based on the discussion with KB: we need two different types of global errors: 

- nonblocking global error: an error notification that not blocks the user from doing further interaction.
- blocking global error: an error notification that at the same time locks the UI and prevents the user from further interaction until the error is resolved. Prime example: the connection to the backend is lost, and the UI is locked until connection is resumed.

**Comment by Mgranfie** [comment]
Ok taking a pass at formatting this story.. feedback?

As a user of the ALM product, I need to understand when an error occurs in the system and what I should do in response to that error, so that I can resolve the situation in a knowledgeable and timely manner.

Verification Criteria:

* Error messages are preseneted in a manner that allow the user to understand the context of the message as system wide or field level specific.
* The messages presented to the end user are understandable
* The messages presented to the end user are actionable
* UX has access to a single source file where text for the messages can be edited

**Comment by Mgranfie** [comment]
Some of these should be individual stories like this one:

also to investigate: error for when a user has no internet connection (specific to the mobile use cases)

@mindreeper2420 some of these higher level specific error use cases, would be good to break out into individual stories...

**Comment by Mgranfie** [comment]
@mindreeper2420  is this story a reference to RHUAP-297?[https://patternfly.atlassian.net/browse/RHUAP-297](url)

**Comment by mindreeper2420** [comment]
@Mgranfie yes - they are the same. I will update the description here to have the link with it for reference.

**Comment by Mgranfie** [comment]
@mindreeper2420 if the story I wrote is correct, please post to the original or change....edit as needed and update the original story for clarity. If it's not clear yet, this can be a follow up for next sprint... let me know.

**Comment by nimishamukherjee** [comment]
@mindreeper2420 @Mgranfie would it make sense to take a step back and look at a notification system which includes successes, errors, alerts, etc, and then dive into this story?

**Comment by Mgranfie** [comment]
@nimishamukherjee  we have a placeholder for notifications in the UI. The actual feature, rules, needs, requirements have not been addressed. It is on our roadmap.

**Comment by nimishamukherjee** [comment]
Thanks @Mgranfie
