### ISSUE TITLE
FOLLOW UP: Display and Update Area Field on Work Item Detail View

### ISSUE THREAD

**Issue by Mgranfie** [fabric8io/fabric8-ux#204]
* Contact Dev, let them know you are their contact person for questions
* Check in with them, on an a periodic as needed basis throughout the sprint
* Assure that this functionality is demoed and meets specifications in the original UX design.

GitHub Issue:

UX
https://github.com/fabric8io/fabric8-ux/issues/129

Dev
https://github.com/fabric8io/fabric8-planner/issues/913

**Comment by mindreeper2420** [comment]
Reached out on 2/24/2017 via the Planner Issue on GitHub. Will follow-through on HipChat next business day.

**Comment by mindreeper2420** [comment]
@nimishamukherjee has this item been merged into the Planner? Were the questions around the interactions resolved?

**Comment by nimishamukherjee** [comment]
@mindreeper2420 this has been merged into planner. No questions from my end.

**Comment by mindreeper2420** [comment]
@nimishamukherjee ok - this issue stays open until we know if something has been merged, so thanks for the update. I'll take a look in the UI and compare vs designs.
