### ISSUE TITLE
WIREFRAME: Drag and Drop in Card View

### ISSUE THREAD

**Issue by Mgranfie** [fabric8io/fabric8-ux#206]
Establish and publish rules for drag and drop in the card view.  This should affect both order of execution, and state changes as the user drags across states in the card view.   It should capture the effect of making changes in the card view to how things will be saved and shown in the list view as well.

UX
https://github.com/fabric8io/fabric8-ux/issues/206

Dev:
https://github.com/fabric8io/fabric8-planner/issues/887

**Comment by catrobson** [comment]
Updated this issue to reflect that we need designs captured for all drag and drop options on the card view before we do follow-up with development.

**Comment by catrobson** [comment]
I've updated the InVision document to add a few more clear statements about expectations of when state change happens, and to clean them up for summit purposes.  They already captured most order of execution interactions clearly, but added a comment about new items being added to the top of order of execution for that status. https://redhat.invisionapp.com/share/3R9PRV192.

Will follow up with Dev as next step.
