### ISSUE TITLE
FOLLOW UP:  Changing Work Item States in Card View 

### ISSUE THREAD

**Issue by Mgranfie** [fabric8io/fabric8-ux#207]
- Contact Dev, let them know you are their contact person for questions
- Check in with them, on an a periodic as needed basis throughout the sprint
- Assure that this functionality is demoed and meets specifications in the original UX design.

GitHub:

https://github.com/fabric8io/fabric8-planner/issues/886

**Comment by mindreeper2420** [comment]
Reached out on 2/24/2017 via the Planner Issue on GitHub. Will follow-through on HipChat next business day.

**Comment by mindreeper2420** [comment]
@Mgranfie - is there a particular wireframe or visual that you want me to reference? I know how it is supposed to work from our discussions, but I could not find an exact design reference. The closest I found is this [Columns w/WI Preview](https://redhat.invisionapp.com/share/XD9ZNX7M7#/210504573_Boardview-Click1), but it does not cover changing the States.

**Comment by catrobson** [comment]
@mindreeper2420 - I suggest that @Essjaysee and I take over this story as part of our work on #206 - there hasn't been anything captured around this and I think we need to wireframe step prior to following up with Dev for the Card View specifically.

**Comment by mindreeper2420** [comment]
@catrobson @Essjaysee I'm ok with that. I already commented on the issue with Vikram, and he is looking at Melody's initial card wireframe for how a user interacts with the cards.

**Comment by catrobson** [comment]
I've updated the InVision document to add a few more clear statements about expectations of when state change happens, and to clean them up for summit purposes:  https://redhat.invisionapp.com/share/3R9PRV192.

Will follow up with Dev as next step.

**Comment by catrobson** [comment]
Reviewed Card view drag and drop from Dev team, looking good.
