### ISSUE TITLE
FOLLOW UP:  Order-of-Execution for Work Items in Iteration

### ISSUE THREAD

**Issue by Mgranfie** [fabric8io/fabric8-ux#209]
- Contact Dev, let them know you are their contact person for questions
- Check in with them, on an a periodic as needed basis throughout the sprint
- Assure that this functionality is demoed and meets specifications in the original UX design.
- Establish and publish the impact and rules of engagement for the order of execution in relationship to the Iterations filter and how it impacts the list and cards view.

GitHub:

Dev
Display Work Item in a Board View

**Comment by catrobson** [comment]
Scoped to list views only - more IxD and Visual Design needed on board views before follow-up.

For this story, UX to verify:
* Drag and drop interactions and visuals are as specified for work item list views
* If the user crosses views (iteration to backlog for example), changes made to the order of execution are saved and reflected across these views.

**Comment by catrobson** [comment]
Looking at prod-preview - the drag and drop is reordering items, but does not follow visual design specs and acts a bit wonky for drop spots.  The reordering is not being save when I switch views.  Will log some bugs and then close this story out and track as overall review and bug tracking from here.

**Comment by catrobson** [comment]
Discussed with development team and this is resolved for now - we will be looking at order of execution again post-summit.
