### ISSUE TITLE
WIREFRAMES: Wizard Home Page, Space Confirmation UI

### ISSUE THREAD

**Issue by Mgranfie** [fabric8io/fabric8-ux#210]
As a user, I would like to be assisted on some common, high level tasks, that are available, and guidance around them.

* Layout needs to be addressed
* Verbiage scrub
* Navigation considerations forward and back need to be worked out...
* Refer to functionality in the http://prod-preview.openshift.io/home build > Kick off a new space and the next dialog after defining the space is the Wizard Home page.

(Notes on changes in comments on this InVision page [here](https://redhat.invisionapp.com/share/PX9U28TBR#/212194232_Scenario1_9)

VC's
* UI wireframes created
* User has clear understanding on what each option on this page will do 
* User has a clear understanding of navigation and confirmation between this screen, the create space screen and where the affirmative and cancel options bring the.
* UI has been vetted with UX + stakeholders (Pete, Todd, Cat...)

**Comment by Essjaysee** [comment]
@pmuir @qodfathr @joshuawilson In the space creation wizard, if the user opts to import code or create code from scratch, at what point would they select the stack and/or pipeline?
