### ISSUE TITLE
WIREFRAME: Space Home Page

### ISSUE THREAD

**Issue by Mgranfie** [fabric8io/fabric8-ux#213]
As a user of the product, any Space I work in, will have a home page, that I can use to view information about that Space.

* Determine controls for the page units
* Determine content for the page
* Create an empty experience for the page
* Create a filled experience

Current page in product:
http://prod-preview.openshift.io/pmuir/BalloonPopGame

UX MockUps (The End to End has some mock ups and ideas of this page.. not all are possible)

* Propose and confirm any ideas on information that would be useful to the various groups at RedHat that are examples of the user base, based on their input and any additional ideas. Email Dev-Tools lead mail list to request what would be one piece of useful content for them on this page.
* Information about the state of some content we have (ie: Open Scenarios) is possible, it will not be possible, in Summit time frame to employ behaviors such as, usage algorithms.
* Consider PatternFly Cards as a dashboard component, vet with Development
* Vet final wireframes with UX, Dev and Stakeholders (Pete, Todd, Cat)

**Comment by muruGanesan** [comment]
Please assign to me...

**Comment by muruGanesan** [comment]
First cut wireframes are created and published in inVision for review 
URL: https://redhat.invisionapp.com/share/K8ASA61ZF

**Comment by muruGanesan** [comment]
https://redhat.invisionapp.com/share/NZATYFVXT#/223261821_Space_Homepage_V05-001

**Comment by muruGanesan** [comment]
update the review comments, once again I need to validate with dev team and close:
 https://redhat.invisionapp.com/share/NZATYFVXT#/223261821_Space_Homepage_-empty-option1-001

**Comment by muruGanesan** [comment]
Reviewed with UX and Dev... I believe it is ready for Visual design.

**Comment by muruGanesan** [comment]
Wireframe is ready for Visual Design

**Comment by muruGanesan** [comment]
@mindreeper2420, @sunilmalagi, @bdellasc, 
Now the Wireframe is ready for Visual Design.
Please let me know if any one of you could help me on visual design.

**Comment by catrobson** [comment]
@muruGanesan I don't think that this is ready for visual design.  I think we need to pull this into the next sprint and work through a few more issues - that top area staying static isn't a good experience for the product as people use it for a while.  

Open issues for me:
* Top section staying static
* Determining whether we should sentence style updates or just a list of items

**Comment by muruGanesan** [comment]
Submitted for Visual design
