### ISSUE TITLE
WORKFLOW: Log In Workflow and process for Summit

### ISSUE THREAD

**Issue by Mgranfie** [fabric8io/fabric8-ux#217]
As a user of the OpenShift.io product, I want to be able to request access to the beta, log in with and or register my Red Hat Developers account, so that I can use the beta product, in a freemium mode.

* Create workflow based on input and feedback from stakeholders and development.
* Review update of workflow with stakeholders and development.
* Post workflow on InVision.
* Understand the capabilities and limitations of KeyCloak, Eloqua RHD, and Openshift.io, and how they influence the workflow and user experience.
* Finalize with dev, how the manual process for summit, will work to confirm a user has been enrolled in the beta program.

VC's
* Work with Tiffany and stakeholders to establish possibilities and limitations
* Follow through with other product point people on capabilities
* Create wireframes based on known workflows
* Post wireframes and review with Dev, UX and Stakeholders

**Comment by catrobson** [comment]
They should only be able to log in with Red Hat Developers, not GitHub.
