### ISSUE TITLE
Font size evaluation

### ISSUE THREAD

**Issue by catrobson** [fabric8io/fabric8-ux#218]
There is a request to increase the base/standard text font size to 14pt for ALM.  We need to evaluate how this would affect the UI, and how it would affect users moving from one Red Hat product to another.  The goal is to consider whether this change would create a jarring experience for cross-product users especially, as the is the main reason to maintain consistency.

Verification Criteria:
* We understand which areas of the current ALM design would change with a font increase, mock it up, and define anything that should not follow base font that previous had if needed
* Mock up/prototype of moving from ALM with 14pt base font to another product UI with 12pt base font to "test" cross-product font change.  OpenShift should be used for test.

**Comment by Mgranfie** [comment]
I would defer to some of the visual and PF folks on this. Are we also
staying with the same font, or is that changing too, as that cold determine
more of the impact than changing the size of the same font.

My 2 cents based on having to recently address this in a product is... if
the font is the same, this should not present a huge problem across
product, as most of our screens are not yet too content heavy. There will
be lot's of spacing tweaks that will happen, and depending on how our
interface is crafted will determine how vast the tweaks are. The left pane
on the planner is at the most risk.

It will surface if we have all of our overflow stories solidified for sure,
which is good to see early on.

Are we also increasing our base screen size along with increasing the font
size?

-Monica

**Comment by Essjaysee** [comment]
I'm curious what the issue is that we would address by increasing the font size.  Is it in preparation for if/when PF increases the base text size?  Is there an accessibility requirement?  Is it so the UI will show better in demos?  Knowing what is driving the request will help us provide an appropriate solution.

**Comment by Mgranfie** [comment]
Good question... is it aiming for higher res systems? If so we should also
be increasing our base screen dimensions....
