### ISSUE TITLE
VISUALS (SPECS): Reorder (Drag/Drop) Work Items in List

### ISSUE THREAD

**Issue by bdellasc** [fabric8io/fabric8-ux#221]
Verification Requirements:
Refer to previous visual stories: [VISUALS: Reorder (Drag/Drop) Work Items in List](https://github.com/fabric8io/fabric8-ux/issues/155) & [VISUALS: Reorder (Drag/Drop) Work Items in List, Part 2](https://github.com/fabric8io/fabric8-ux/issues/190), then:

- Add specifications to previous visuals work
- Post new visual specs to InVision, review with UX team members
- Link to InVision prototypes from this story
- Tag story as "Ready for Development"

**Comment by sunilmalagi** [comment]
https://redhat.invisionapp.com/share/YBAUESBKG

**Comment by sunilmalagi** [comment]
https://redhat.invisionapp.com/share/YBAUESBKG
