### ISSUE TITLE
VISUALS (SPECS): IA

### ISSUE THREAD

**Issue by bdellasc** [fabric8io/fabric8-ux#223]
Verification Requirements:
Refer to previous visual story: [VISUALS: IA](https://github.com/fabric8io/fabric8-ux/issues/93), then:
- Add "Settings" to the top level nav
- Figure out reasonable layout
- Figure out User icon, Area icon, etc
- Add specifications to previous visuals work
- Post new visual specs to InVision, review with UX team members
- Link to InVision prototypes from this story
- Tag story as "Ready for Development"

**Comment by bdellasc** [comment]
Posted mockups to InVision here: [https://redhat.invisionapp.com/share/46B7T58G9](https://redhat.invisionapp.com/share/46B7T58G9)

**Comment by catrobson** [comment]
Adam has implemented first pass.  If we need to do a review we can add a new story.
