### ISSUE TITLE
VISUALS:  Blank state image for profile pictures

### ISSUE THREAD

**Issue by catrobson** [fabric8io/fabric8-ux#224]
Need a blank state profile picture image.  

Will need to be in two sizes:

-  one for header bar next to name, list/board view, detail panel
-  one for the profile settings page

**Comment by bdellasc** [comment]
I had done an initial treatment for two states of the user image in the context of the Work Item detail view:
1. No User Assigned
2. User assigned, but with a default profile image

They used the same icon, just gray vs. dark gray on a white background See slide 24 in the [Iteration flow](https://redhat.invisionapp.com/share/FR9R8G6B9)

So, this is already partway there, would just need to look at the other scenarios (header bar & profile settings page) once the interaction design is complete.

**Comment by catrobson** [comment]
Thanks @bdellasc - closing this issue as I think we're all set now.
