### ISSUE TITLE
WIREFRAMES: User Home Page Logged in 

### ISSUE THREAD

**Issue by Mgranfie** [fabric8io/fabric8-ux#225]
A a user of Openshift.io when I am logged into the product, I want to see information that is guiding and useful to me, so that I can quickly get started on tasks or existing work, with little effort.

Requirements:

- Empty/First use scenario of the page (no content in some units on the page)
- Repeat use scenario (content in some units on the page)
- Access to on line documentation for learning more
- Opportunity to create a new space.
- List of existing spaces, if there are any.
- What's new, static content
- Resource Usage (Stretch goal)

VC's
* Interaction design and content is captured in wireframes.
* Wireframes are posted to InVision
* Wireframes are reviewed and confirmed with UX, Stakeholders and Development.

**Comment by jryhanyc** [comment]
For review: [1st draft wireframes](https://redhat.invisionapp.com/share/XZAOBAOPB#/221480596_A-0100-Home-LoggedIn)

**Comment by muruGanesan** [comment]
Space home page concept for review:
URL: https://redhat.invisionapp.com/share/MZAS1EXJ5#/222645775_Space_Dashboard_V03-002.

**Comment by Mgranfie** [comment]
Hey Muru... excited to  look at this. InVision does this strange thing
where it scales the UI in the view mode... If you look in the lower right
hand corner of the screen there is a gear and in that setting you can
choose to scale to screen size in the drop down and there is a checkbox to
apply to all screens... if you flip that on, we will be able to see the
image.

It's not obvious and we all still forget sometimes :)
