### ISSUE TITLE
VISUALS (SPECS): Space Home Page

### ISSUE THREAD

**Issue by bdellasc** [fabric8io/fabric8-ux#228]
Verification Requirements:
Refer to previous visual story: [VISUALS: Space Home Page](https://github.com/fabric8io/fabric8-ux/issues/214), then:

- Add specifications to previous visuals work
- Post new visual specs to InVision, review with UX team members
- Link to InVision prototypes from this story
- Tag story as "Ready for Development"

**Comment by catrobson** [comment]
@sunilmalagi - can you link in your latest visual designs?

**Comment by sunilmalagi** [comment]
Sure, here it is...
https://redhat.invisionapp.com/share/TNAXIS9UW
