### ISSUE TITLE
VISUALS (SPECS): Menu (via Work Items kebab)

### ISSUE THREAD

**Issue by bdellasc** [fabric8io/fabric8-ux#242]
Verification Requirements: Refer to previous visual story: [VISUALS: Menu (via Work Items kebab)](https://github.com/fabric8io/fabric8-ux/issues/241), then:
- Add specifications to previous visuals work
- Post new visual specs to InVision, review with UX team members
- Link to InVision prototypes from this story
- Tag story as "Ready for Development"

**Comment by bdellasc** [comment]
Posted mockup & specs to [InVision](https://redhat.invisionapp.com/share/EYANJENG7)

**Comment by catrobson** [comment]
@bdellasc - is this complete and ready to close?

**Comment by bdellasc** [comment]
Yes, sorry. Closing it now.
