### ISSUE TITLE
VISUALS: Areas - Manage 

### ISSUE THREAD

**Issue by bdellasc** [fabric8io/fabric8-ux#254]
Verification Conditions:
Refer to [Wireframes: Areas - Create New Areas UI](https://github.com/fabric8io/fabric8-ux/issues/160) story, then:
- Create visual designs, utilizing PatternFly when appropriate
- Post designs to InVision
- Tag story with “ux review”
- Review with UXD Team members

**Comment by catrobson** [comment]
Was implemented using PatternFly visuals.  Closing story as not needed.
