### ISSUE TITLE
VISUALS (SPECS): Areas - Manage

### ISSUE THREAD

**Issue by bdellasc** [fabric8io/fabric8-ux#255]
Verification Requirements: Refer to previous visual story: [VISUALS: Areas - Create New Areas UI](https://github.com/fabric8io/fabric8-ux/issues/254), then:
- Add specifications to previous visuals work
- Post new visual specs to InVision, review with UX team members
- Link to InVision prototypes from this story
- Tag story as "Ready for Development"

**Comment by catrobson** [comment]
Was build using PatternFly patterns and visual styles.  Closing issue.
