### ISSUE TITLE
VISUALS: User Home Page Not Logged in 

### ISSUE THREAD

**Issue by bdellasc** [fabric8io/fabric8-ux#258]
Verification Conditions:
Refer to [Wireframes: User Home Page Not Logged in](https://github.com/fabric8io/fabric8-ux/issues/188) story, then:
- Create visual designs, utilizing PatternFly when appropriate
- Post designs to InVision
- Tag story with “ux review”
- Review with UXD Team members

**Comment by mindreeper2420** [comment]
This should be reviewed by Todd as well.

A corresponding dev story is located here: https://github.com/openshiftio/www.openshift.io/issues/35

**Comment by jryhanyc** [comment]
[Visual designs – desktop](https://redhat.invisionapp.com/share/M2B1IDIWB)
[Visual designs – mobile]( https://redhat.invisionapp.com/share/W3B1IKPD8#/225847189_A-0450-Home-NotLoggedIn_Mobile)

**Comment by catrobson** [comment]
@jryhanyc looks pretty good.  Just the registration complete page needs a button update, and I had one question on the status dropdown that I left in InVision.  Let's fix those and then we can review with Todd before closing.
