### ISSUE TITLE
VISUALS: User Home Page Logged in

### ISSUE THREAD

**Issue by bdellasc** [fabric8io/fabric8-ux#260]
Verification Conditions:
Refer to [Wireframes: User Home Page Logged in](https://github.com/fabric8io/fabric8-ux/issues/225) story, then:
- Create visual designs, utilizing PatternFly when appropriate
- Post designs to InVision
- Tag story with “ux review”
- Review with UXD Team members

**Comment by catrobson** [comment]
@jryhanyc can you post the visual design link and close?

**Comment by jryhanyc** [comment]
[Final visual design concept](https://redhat.invisionapp.com/share/JKBG0YIEX)
