### ISSUE TITLE
Sync & Share

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8io/fabric8-ux#281]
As part of the push for the next 2-3 weeks, Muru and I will be staying in sync regarding any ongoing items with the development team, as well as UXD updates and plans. Any information gathered from this sync will be shared with the relevant teams and individuals.

**Comment by muruGanesan** [comment]
Yes, I agree.
Thanks Adam!

**Comment by muruGanesan** [comment]
Adam, could please share the InVision link for nested (Tree structured) work-items?

**Comment by mindreeper2420** [comment]
Hi Muru - here is the link: https://redhat.invisionapp.com/share/YVA4PGYA3 .

Everything link and it's associated GitHub Issue is located here: https://fabric8io.github.io/fabric8-ux/invision-links.html. You can also find all of the prototypes inside of InVision under Red Hat and then by searching ALM_. That will give you everything from this project, outside of the invision-links list (if needed).
