### ISSUE TITLE
VISUALS:  Error page

### ISSUE THREAD

**Issue by catrobson** [fabric8io/fabric8-ux#284]
For summit, we want to create a generic, maybe fun and snarky, error page so users know the current page they are trying to access didn't work for some reason, and they should try later or reload.

May want to reach out to Tiffany and James Cobb for example of what they did for red hat developers as an example or reference to build from.

Verification criteria:
* Page created
* Page reviewed with Dana, Cat, Monica, Brian, SJ
* Page sent to development team

**Comment by jryhanyc** [comment]
[Doc with ideas + best practices](https://docs.google.com/a/redhat.com/document/d/1XpUG-G1cPh7JK9EPrrOQoeN6C2ZHLcl9lk4O8d6-qzs/edit?usp=sharing)

**Comment by jryhanyc** [comment]
1st draft ideas [here](https://redhat.invisionapp.com/share/MQAQIVKP8)

**Comment by jryhanyc** [comment]
[Feedback spreadsheet](https://docs.google.com/a/redhat.com/spreadsheets/d/1XYfGFcovqoQYrGEbUPnOfWjP2ck1P7raPEp4EHMNRFY/edit?usp=sharing)
