### ISSUE TITLE
VISUALS (SPECS): Holistic Review of WI Detail Panel

### ISSUE THREAD

**Issue by bdellasc** [fabric8io/fabric8-ux#286]
Verification Requirements: 
Refer to previous visual story: [VISUALS: Holistic Review of WI Detail Panel](https://github.com/fabric8io/fabric8-ux/issues/285), then:
- Add specifications to previous visuals work
- Post new visuals to InVision, review with UX team members
- Link to InVision prototypes from this story
- Tag story as "Ready for Development"

**Comment by bdellasc** [comment]
Posted initial pass with open questions for UX team

**Comment by mindreeper2420** [comment]
Here are screenshots of the updated Description Input:

**Description - Less:**
<img width="966" alt="description_less" src="https://cloud.githubusercontent.com/assets/4032718/24116042/c6751cea-0d7b-11e7-90e8-af53808c3c46.png">

**Description - More:**
<img width="967" alt="description_more" src="https://cloud.githubusercontent.com/assets/4032718/24116051/cdf1c0cc-0d7b-11e7-9438-ec02e63a6efc.png">

**Description - Less - Editing:**
<img width="969" alt="description_edit_less" src="https://cloud.githubusercontent.com/assets/4032718/24116056/d2764c62-0d7b-11e7-8bea-ce59bf1a0cc3.png">

**Description - Expanded - Editing:**
<img width="966" alt="description_edit_more" src="https://cloud.githubusercontent.com/assets/4032718/24116063/d675a678-0d7b-11e7-9cab-b78dd822486e.png">

**Comment by bdellasc** [comment]
The plan is to sit with Adam @ Dana to get these pieces implemented as designed instead of spec'ing them.
