### ISSUE TITLE
VISUALS (SPECS): Error page

### ISSUE THREAD

**Issue by bdellasc** [fabric8io/fabric8-ux#287]
Verification Requirements: Refer to previous visual story: [VISUALS: Error Page](https://github.com/fabric8io/fabric8-ux/issues/284), then:
- Add specifications to previous visuals work
- Post new visual specs to InVision, review with UX team members
- Link to InVision prototypes from this story
- Tag story as "Ready for Development"

**Comment by jryhanyc** [comment]
[1st pass](https://redhat.invisionapp.com/share/JNAXQEJM4) of spec PSD file
