### ISSUE TITLE
WIREFRAMES: Create a link between work items

### ISSUE THREAD

**Issue by Mgranfie** [fabric8io/fabric8-ux#29]
Personas: All

As a user of the ALM tool, I should be able to establish a relationship to another work item, via a URL.

Experience 1603E131
InVision Prototype:
https://redhat.invisionapp.com/share/XT8V1XO7H

JIRA Issues:
Discovery: https://patternfly.atlassian.net/browse/RHUAP-316
Story: https://patternfly.atlassian.net/browse/RHUAP-334

Dev Core:
https://github.com/almighty/almighty-core/issues/307

**Comment by mindreeper2420** [comment]
Here is the Discovery GitHub Issue related to this: #3

**Comment by Mgranfie** [comment]
@joshuawilson Links UI has been revised and is ready for development

**Comment by Mgranfie** [comment]
@kwk @nimishamukherjee @mindreeper2420 @SMahil Hi All, I have created a quick, low fidelity pass at a solution for drilling down on Related Links on a WI. Take a look and lmk if you have any questions. This is a first pass to keep us from being blocked.

![wi_links_drilldown_ui](https://cloud.githubusercontent.com/assets/18149547/20730897/ef70af42-b655-11e6-8449-9021f73334b5.jpg)

**Comment by joshuawilson** [comment]
@harrybabu please take a look at the above design

**Comment by kwk** [comment]
Hi Monica,

thanks for sharing this. I wonder if the original WI shall be selected in
the list all the time. If we have a "back" navigation link, what's the
benefit of having the original WI selected in the list instead of moving
the selection to "LinkA" or "LinkB"?

Thanks
Konrad

**Comment by Mgranfie** [comment]
It's a bit quirky, as we are working to get a base solution in the product.
The idea being, that you retain your original context, so like in sketch 3,
if you have drilled down 3 levels of links, you can easily, in one click
get back to your original WI. I don't know if this is perfect, but I think
for now it is useable. Based on this, what are your thoughts and
impressions?....

**Comment by kwk** [comment]
Hi Monica,

I suspected the quick "go back to first context" the reasons for the way
you sketched it out. I only worry about the discrepancy of having made a
selection and showing something differently. If we do so, we might have to
mark the selected item from the list in a different color (e.g. grey). So
whenever it is highlighted using the primary selection color (e.g. blue)
you should see what you have selected in the details view. But whenever
you've moved on, it should have a "secondary selection highlight".

As an alternative, but completely changing the way we operate right now,
here's an actual example of navigating through "related artists" in the
Spotify Web Player. I searched for Bob Dylan and selected the artist, then
I clicked on the related artist "Paul Simon", from there I clicked on the
related artist "Simon & Garfunkel". Notice how in the picture only the last
visited item is shown: "Paul Simon".



Once I click on the greyed out area to the left, I get back to "Paul Simon"
and it shows me the greyed out "Bob Dylan" section on the left, from where
I started:


​
I've been getting used to this and it works good for me. Have you/we
considered such an approach? I don't quite remember all ideas brought to
the table.

Regards,
Konrad

**Comment by Mgranfie** [comment]
@kwk Thanks for the ideas and examples!!

I like using the lightbox idea to give focus to the WI. However, the idea of leaving the list of WI's int he Backlog, an Iteration or an Agile Board column, exposed and accessible, is to allow users to switch between WI's, leaving the WI open, without having to navigate in and out of a UI, for easy context switching. The equivalent in SF might be a list of Genres on the left. But because SF is not a productivity tool, the use case scenarios are a little different and focused more on browsing and just the drill down activity and not switching Genres.
I was curious about your idea, so I mocked up the WI with a light box and the feedback was that the implied behavior when a lightbox is presented, is that clicking out of the WI would close the work item and that they would think they could not click between work items, to change context, limiting the ability to traverse WI's and leave the WI detail pane open.

This is the screen that I used to match the SF solution:  Again, their use and intent is a little different than ours. But I think we still might be as cool as them!
![wi_links_nav_a](https://cloud.githubusercontent.com/assets/18149547/20765996/a1dde904-b702-11e6-9880-29b58106dfbb.png)


To address your concern on how to keep the context and know you are in a different WI, a couple of us brainstormed a little and talked about including the original WI Title on par with the < Back button, here in this sketch, which confused people. We also considered breadcrumbs, but these will grow long and unusable. 

![wi_links_nav_b](https://cloud.githubusercontent.com/assets/18149547/20766406/5f7dbd08-b704-11e6-98bb-2fcea1e149f4.png)

In revisiting the goal of this solution, was to address a 2 - 5 drill down level in a simple and direct way, while keeping context and still allowing the user to traverse WI's in the list. I agree that this doesn't scale and moving forward may need additional thought, if we find that users are conducting deeper drill downs. 

Based on these goals and functions, and your use of SF v.s the use cases here, any more thoughts or ideas that might still influence? If not am thinking for this pass, the we run with this as is, see how it feels in use and iterate from there? ....

**Comment by kwk** [comment]
Hi Monica,

thank for exploring so many directions and for being open to feedback.

Maybe this annotated image shows what subtle change I had in mind when:

[image: Inline image 1]
Most of it has to do with the changed color of the selection.

If I understand you correctly, graying out the list of WIs will disturb the
user as she/he thinks no selection can be made in it, right?

As a visual hint, my change to a more subtle selection color shouldn't
change the user's way she/he thinks about the list. A selection can still
be made.

Regards
Konrad

**Comment by Mgranfie** [comment]
@kwk am interested to see your idea, the image did not show up... can you post again?

**Comment by kwk** [comment]
@Mgranfie Here's the image.
![wi-list-navigation](https://cloud.githubusercontent.com/assets/193408/20796357/14337342-b7d6-11e6-89e8-1e7e7d4e76b2.png)

**Comment by Mgranfie** [comment]
@kwk Ah OK, great picture! Remote design can be a challenge : ) Sure I am good with bumping down the highlight of the individual item... let's go for it and see how it feels!

**Comment by kwk** [comment]
@almighty/ui is anyone willing to take this over to the actual frontend?

**Comment by Mgranfie** [comment]
A screen was added to describe the behavior for creation of links in context. Only mocked up in the DT only version, but applies to the Mobile version as well.

https://redhat.invisionapp.com/share/M28SSTLRJ#/212315850_DesktopAddLink_09
