### ISSUE TITLE
WIREFRAME: User Profile Page

### ISSUE THREAD

**Issue by Mgranfie** [fabric8io/fabric8-ux#301]
As a user of OS.io I want to be able to edit (public?) attributes/information that is listed in my profile, so that I understand what is viewed by the (public?).

* Determine what attributes will be surfaced on this page and any requirements for them.
* Understand where this page will sit in the product
* Create UI and understand any navigation around this page.
* Consider first use and repeated use scenarios.

VC's
* Create wireframes
* Review wireframes with UX + Stakeholders.
* Post to InVision

GitHub Related:

https://github.com/fabric8io/fabric8-ui/issues/193
https://github.com/almighty/almighty-core/issues/761

**Comment by catrobson** [comment]
@jryhanyc - According to @pmuir we now have the ability for the user to update their image by providing a new URL, but we can't implement image storage for now.  Can you think about how we present that experience in your Profile work?

**Comment by jryhanyc** [comment]
@catrobson will do

**Comment by jryhanyc** [comment]
[Latest draft wireframes](https://redhat.invisionapp.com/share/FDB31HXVC)

**Comment by catrobson** [comment]
Let's talk about this and the OAuth story in planning tomorrow briefly to figure out where we need this to head.

**Comment by catrobson** [comment]
Jessica's latest wireframes can be found here:  https://redhat.invisionapp.com/share/KQB6LEHM8
