### ISSUE TITLE
VISUALS: Icons/graphics for Create Space Wizard

### ISSUE THREAD

**Issue by Essjaysee** [fabric8io/fabric8-ux#302]
Verification Conditions:
- Using the wireframes as a guide, create screens that utilize PatternFly components where possible and deviate from base PatternFly components where necessary
- Create other visual elements needed to complete the designs
- Gather feedback from other visual designers ( @bdellasc @jryhanyc )
- Integrate feedback into visuals

Each of the four options in the Create Space Wizard needs an icon or graphic.  https://redhat.invisionapp.com/share/QNAOD7PF4#/221494633_Create_Space_-_Initial_Tasks

**Comment by sunilmalagi** [comment]
https://redhat.invisionapp.com/share/Z9B9OWP5S
