### ISSUE TITLE
WIREFRAME: First Use of Planner Boards - Blank

### ISSUE THREAD

**Issue by Mgranfie** [fabric8io/fabric8-ux#303]
As a user of OS.io, I want to to be welcomed into a blank boards environment with some helpful information or instruction, so that I understand what the environment is for or anything special or particular about it, so that I can use a large portion of the UI without any further efforts around learning.

* Understand what information or instruction might be helpful for a user when seeing the boards view for the first time, or what unique information might help the user gain insight.
* Create wireframes for a few different approaches or ideas/concepts.

VC's
* Post wireframes to InVision
* Review with UX, stakeholders and dev

**Comment by catrobson** [comment]
Wireframes posted and ready for visual design in the Boards wireframe set.
Wireframe Set: https://redhat.invisionapp.com/share/XD9ZNX7M7

Specific empty state image: https://redhat.invisionapp.com/share/XD9ZNX7M7#/223238952_Boardview-Empty2
