### ISSUE TITLE
Changes to Statuses InVision Links List

### ISSUE THREAD

**Issue by bdellasc** [fabric8io/fabric8-ux#313]
Verification Conditions:
Please add/change these statuses:
- Not Yet Started (Key text - “Planned- current goal by UXD”) - purple bg
- TBD (Key text - “Unplanned - future goal by UXD”) - light gray bg with dark gray text or something that looks disabled

**Comment by mindreeper2420** [comment]
Screenshot of new Legend and an example in the table:
<img width="1920" alt="screen shot 2017-03-07 at 5 31 14 pm" src="https://cloud.githubusercontent.com/assets/4032718/23681181/f2b2d4ca-035b-11e7-8dbf-560b2fa72a5a.png">

**Comment by mindreeper2420** [comment]
PR is located here: https://github.com/fabric8io/fabric8-ux/pull/316

**Comment by mindreeper2420** [comment]
Closing as PR merged. Confirmed changes on production site.
