### ISSUE TITLE
WIREFRAME: Obsidian Launcher [Part 1]

### ISSUE THREAD

**Issue by catrobson** [fabric8io/fabric8-ux#317]
Evaluate the current Obsidian Launcher UI against PatternFly, OpenShift, and Fabric8 to ensure consistency of pattern and style usage.

Staged version: http://start.prod-preview.openshift.io/wizard/obsidian-new-quickstart/0

Verification Criteria:
* UI suggestions captured and shared with PatternFly, OpenShift, Fabric8 UX teams for a final check of consistency by many
* Final UI improvements shared back to Obsidian team

Linked Issue in Obsidian repo:
https://github.com/obsidian-toaster/generator-frontend/issues/31

**Comment by catrobson** [comment]
UXD Stakeholders:  
* Catherine Robson - overall strategist
* Sj Clark for Fabric8 wizard that should have same look/feel.  
* Serena Doyle for OpenShift that will also link off off to this Launcher

**Comment by jryhanyc** [comment]
[Draft wireframes](https://redhat.invisionapp.com/share/SXAWB8JNA) based on initial feedback and conversation with Serena about OpenShift Mall wizard behavior.

**Comment by jryhanyc** [comment]
[Updated wireframes](https://redhat.invisionapp.com/share/7DAWWLMAH) addressing:

1. Current implementation
2. Proposed implementation
3. A card view for functional quickstart projects
4. Notification for scenario when a user wants to change project selection
