### ISSUE TITLE
WORKFLOWS:  Obsidian launcher

### ISSUE THREAD

**Issue by catrobson** [fabric8io/fabric8-ux#318]
Work with Obsidian team to understand use case flows for guiding users through some project setups.

Verification Criteria:
* Meetings with Obsidian team recorded and captured
* Flows discussed captured, documented, shared with Obsidian team for further refinement
* Any outstanding questions documented

Obsidian issue: 
https://github.com/obsidian-toaster/generator-frontend/issues/32

**Comment by jryhanyc** [comment]
[Initial notes/review](uhttps://docs.google.com/a/redhat.com/document/d/1j7kXwB3AbjdnACiM3PaIr2wAaLT8Qy26P8zL6pL-QsI/edit?usp=sharingl)

**Comment by jryhanyc** [comment]
[Notes from initial meeting](https://docs.google.com/a/redhat.com/document/d/1j7kXwB3AbjdnACiM3PaIr2wAaLT8Qy26P8zL6pL-QsI/edit?usp=sharing)

**Comment by jryhanyc** [comment]
[User flows](https://redhat.invisionapp.com/share/5EAV875M8#/223693837_A-0100-IA)
