### ISSUE TITLE
VISUALS: User Profile

### ISSUE THREAD

**Issue by bdellasc** [fabric8io/fabric8-ux#320]
Verification Conditions:
Refer to [Wireframes: User Profile Page](https://github.com/fabric8io/fabric8-ux/issues/301) story, then:
- Create visual designs, utilizing PatternFly when appropriate
- Post designs to InVision
- Tag story with “ux review”
- Review with UXD Team members

**Comment by catrobson** [comment]
Dan is implementing based off of Jessica's rather high fidelity wireframes.  Suggest just having a check-in as part of the review process rather than building visual designs.
