### ISSUE TITLE
VISUALS (SPECS): User Profile Page

### ISSUE THREAD

**Issue by bdellasc** [fabric8io/fabric8-ux#321]
VISUALS (SPECS):

Verification Requirements: 
Refer to previous visual story: [VISUALS: User Profile Page](https://github.com/fabric8io/fabric8-ux/issues/320), then:
- Add specifications to previous visuals work
- Post new visual specs to InVision, review with UX team members
- Link to InVision prototypes from this story
- Tag story as "Ready for Development"

**Comment by catrobson** [comment]
Dan is implementing without detailed specs required.  Closing this issue.
