### ISSUE TITLE
WIREFRAME: Additional Global Errors designs

### ISSUE THREAD

**Issue by Mgranfie** [fabric8io/fabric8-ux#334]
A page that communicates to the user that the server is not able to be found, therefore fully interrupting use of the product.

5. HTTP ERROR 401 (UNAUTHORIZED)
This error happens when a website visitor tries to access a restricted web page but isn’t authorized to do so, usually because of a failed login attempt.

4. HTTP ERROR 400 (BAD REQUEST)
This is basically an error message from the web server telling you that the application you are using (e.g. your web browser) accessed it incorrectly or that the request was somehow corrupted on the way.

3. HTTP ERROR 403 (FORBIDDEN)
This error is similar to the 401 error, but note the difference between unauthorized and forbidden. In this case no login opportunity was available. This can for example happen if you try to access a (forbidden) directory on a website.

2. HTTP ERROR 404 (NOT FOUND) *Done
Most people are bound to recognize this one. A 404 error happens when you try to access a resource on a web server (usually a web page) that doesn’t exist. Some reasons for this happening can for example be a broken link, a mistyped URL, or that the webmaster has moved the requested page somewhere else (or deleted it). To counter the ill effect of broken links, some websites set up custom pages for them (and some of those are really cool).

And the most common HTTP error of all is……….

1. HTTP ERROR 500 (INTERNAL SERVER ERROR)
The description of this error pretty much says it all. It’s a general-purpose error message for when a web server encounters some form of internal error. For example, the web server could be overloaded and therefore unable to handle requests properly.

http://royal.pingdom.com/2009/05/06/the-5-most-common-http-errors-according-to-google/

See Spreadsheet
https://docs.google.com/a/redhat.com/spreadsheets/d/1Y4_v5Xo-qKFLMuGFHHEdVy26bTG8I-S_fVogO-frbFg/edit?usp=sharing

**Comment by muruGanesan** [comment]
I will look at Jessica's error page as reference & I will also get information from Dev team and create  unique page templates

**Comment by muruGanesan** [comment]
Hi Jessica,
 Could share the approved design layout (Ninja) for error message page?

**Comment by jryhanyc** [comment]
@muruGanesan @Mgranfie [Error page spec file](https://redhat.invisionapp.com/share/JNAXQEJM4)

**Comment by catrobson** [comment]
@muruGanesan any updates on this?

**Comment by muruGanesan** [comment]
I am moving this to sprint 129 C.

**Comment by catrobson** [comment]
@muruGanesan - did you get copy editing feedback from Docs and we can now call this closed?

**Comment by muruGanesan** [comment]
@catrobson - Yes, we can close
