### ISSUE TITLE
WIREFRAMES: Recommendations – Home Page Not Logged in

### ISSUE THREAD

**Issue by jryhanyc** [fabric8io/fabric8-ux#339]
As a user of Fabric8, I want to be able to review general recommendations (provided by Bayesian) when logged out of the platform. 

VC:
- Promotion for user to sign up for platform to receive full recommendations
- Search and analyze a stack (user provided information)
- View current recommendations from Bayesian

[Wireframes](https://redhat.invisionapp.com/share/7XAIMZBBK) (page 4)
[Github user story reference](https://github.com/fabric8io/fabric8-ux/issues/188)

Review with stakeholders + UX team

#188

**Comment by mindreeper2420** [comment]
@jryhanyc - there is already some placeholder info on openshift.io around this, if you'd like to take a look at it. Once your designs are complete, I can transition them to the site in wireframe form.

**Comment by jryhanyc** [comment]
@mindreeper2420 thanks! I've seen a few screenshots and will look in more detail as I start working on the user home page logged out.

**Comment by catrobson** [comment]
This will not be done at this point in time, closing this issue.
