### ISSUE TITLE
WIREFRAMES: How to view nested iterations

### ISSUE THREAD

**Issue by Mgranfie** [fabric8io/fabric8-ux#340]
As a user I want the ability to see if an iteration is nested and understand where the iteration sits in the hierarchy, so that the relationships of the iterations is obvious to me.

* Confirm and understand use cases that support the need and use of nested iterations.
* Understand and decide if the hierarchy of the iterations needs to be surfaced in the planner UI.
* Establish how to display nested iterations, while considering infinite extensibility on the nesting.
* Create a wireframed solution and review with UX, Dev and Stakeholders.

GitHub Planner Issue:
https://github.com/fabric8io/fabric8-planner/issues/1171

Related:
fabric8io/fabric8-planner#1170

**Comment by catrobson** [comment]
@Essjaysee - anything in particular you want this story around for still, or should we close and open if there are particular design tasks we need to take on moving forward?

**Comment by Essjaysee** [comment]
No, I think this version is closed.  I would like to get some testing done on it though and see how users perceive it.  Separate story?

**Comment by catrobson** [comment]
+1 separate story
