### ISSUE TITLE
WIREFRAME – Bayesian data visualization

### ISSUE THREAD

**Issue by jryhanyc** [fabric8io/fabric8-ux#346]
As a user, I want to review data visualizations of the following stack level and dependency information in the build report:

- Popularity (pulled from GitHub and other sources)
- Issue metrics (open/closed issues)
- Commits
- Version information
- License
- Security
- Code metrics
- Direct declared dependencies

VC:
- Share with ALM stakeholders
- Review with Matthias and dev team

**Comment by jryhanyc** [comment]
[Visual design](https://redhat.invisionapp.com/share/XHB29A9RP#/226096695_A-0100-Bayesian-Overview)

- Missing security data

**Comment by catrobson** [comment]
I think there are some open questions that came out of the demo, let's pull this story into 129c to resolve those before closing.

**Comment by jryhanyc** [comment]
[Draft 2 of visual designs](https://redhat.invisionapp.com/share/26B53ZVMZ)

**Comment by jryhanyc** [comment]
[A few more updates](https://redhat.invisionapp.com/share/7UB5SXBHE)
