### ISSUE TITLE
Proposal for Link Management

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8io/fabric8-ux#352]
I'd like to propose that we remove links to visual designs if they are in need of an update, either based on wireframe changes or new findings. There is confusion as to what visuals designs should match up with wireframes when a wireframe is more up-to-date than the corresponding visual design.

Task:
- [ ] Remove old visual design links that do not match corresponding wireframes
- [ ] Mark those visual designs back to 'In Progress'
- [ ] Keep 'Last Updated' date as-is, until new visual designs are complete

Stakeholders:

- @bdellasc 
- @jryhanyc 
- @Mgranfie

**Comment by catrobson** [comment]
@mindreeper2420 - is this still a problem we should resolve?

**Comment by mindreeper2420** [comment]
@catrobson I'm not sure. I know there was a mention of going to direction that PatternFly uses for uploaded finished designs, but that is on hold until after Summit. I do not know how much (or if) people are still confused by the ongoing changes to designs.

**Comment by catrobson** [comment]
Ok, closing this for now until something actionable comes up around needing improvement.
