### ISSUE TITLE
FOLLOW UP: Revised Navigation

### ISSUE THREAD

**Issue by Mgranfie** [fabric8io/fabric8-ux#357]
Once there is an answer on if settings will be included for Summit and once the Profiles UI is complete... the revised navigation should be reviewed with Todd and Pete.

* Proposed refinements are signed off on by T+P

**Comment by catrobson** [comment]
@Mgranfie can you share your latest design work with me either in InVision or as a Sketch file?  I don't think I have access to the latest updates.

**Comment by catrobson** [comment]
Had to update navigation given some changes to settings for Summit.  Will be reviewing with Pete and Todd today.

https://redhat.invisionapp.com/share/R2AWXA6DU

**Comment by catrobson** [comment]
Reviewed and Todd, Pete, Joshua.  Made some last changes.   https://redhat.invisionapp.com/share/R2AWXA6DU
