### ISSUE TITLE
VISUALS: Review UI component visuals with devs

### ISSUE THREAD

**Issue by bdellasc** [fabric8io/fabric8-ux#359]
Based on list, walk through the UI with Dev and have them fix visuals-related issues.

**Comment by sunilmalagi** [comment]
I need more clarification on this, which are the module/story I need to concentrate?  Do we have a list of the same?

**Comment by bdellasc** [comment]
@muruGanesan said he would go through the list and pull the items from the larger list that you'd need to look at with the devs. I'd imagine he would point to that subset of items from this story to give you more clarification. Muru, can you confirm please?

**Comment by muruGanesan** [comment]
Sure, I will work with Sunil  and Dev team, close the visual issues as much as possible. If required we will connect through call. I will start this work from 29th March 2017.

**Comment by catrobson** [comment]
Thanks @muruGanesan and @sunilmalagi - let's plan to pull this into Sprint 129c

**Comment by sunilmalagi** [comment]
Here is the InVision link for my review comments
https://redhat.invisionapp.com/share/2SBFMXB86
