### ISSUE TITLE
Visual Design [Desktop] - List View

### ISSUE THREAD

**Issue by bdellasc** [fabric8io/fabric8-ux#36]
Corresponding UXD JIRA Story: [RHUAP-204](https://patternfly.atlassian.net/browse/RHUAP-204)

InVision link: [ALM_AddWorkItem_DT_Visuals](https://redhat.invisionapp.com/share/NU8YPHLJP)

**Comment by bdellasc** [comment]
@joshuawilson I posted the flow markup in InVision. Commenting should be enabled in InVision, so please let me know if there's any problems. Please see my JIRA story comments for the link to InVision. If you could also tag the appropriate developers for this, I'd appreciate it. Let me know how the markup works for you guys. Thanks!

**Comment by joshuawilson** [comment]
@bdellasc @mindreeper2420 I don't have permissions to view the InVision link. I also don't have an account on the PF jira, so I can't comment there.

**Comment by mindreeper2420** [comment]
@joshuawilson I signed out of InVision and can still view the link - are you possibly logged in under another account in some way?

**Comment by bdellasc** [comment]
Adding the InVision link here for this story until we can get folks added to the Jira system. We're ultimately aiming to keep any links, etc only in our JIRA stories so we don't have to maintain two sets of information that can potentially get out-of-date: [ALM_AddWorkItem_DT_Visuals](https://redhat.invisionapp.com/share/NU8YPHLJP)

**Comment by bdellasc** [comment]
Adding links to wireframes & visuals (for future/continuing reference):
[Wireframes Flow](https://redhat.invisionapp.com/share/Y39KFTAE7)
[Visuals Flow](https://redhat.invisionapp.com/share/HJ9YNYX2T)
