### ISSUE TITLE
FOLLOW UP: Access Keys for Menus

### ISSUE THREAD

**Issue by Mgranfie** [fabric8io/fabric8-ux#361]
All menus need to have access keys defined and assigned. 

* Access keys must be exclusive to the view 
* Access keys must be consistent across the product per priority of use
* Access keys should follow 504 + 508 accessibility guidelines

VC's
* Assignment of access keys should be defined and listed out
* Assignments for implementation should be reviewed and communicated out to UX and Dev

**Comment by catrobson** [comment]
@Mgranfie completed the access key listing here:  https://docs.google.com/spreadsheets/d/1KglEj4LHhSXO55ksfUgl3jZv6WihibTGFUQixwOMM5w/edit
