### ISSUE TITLE
WIREFRAME: Username & OAUTH page

### ISSUE THREAD

**Issue by catrobson** [fabric8io/fabric8-ux#365]
When the user logs into openshift.io for the first time, they will go through the following flow:

1. Log in on logged out page (or click on link in an e-mail)
2. Log into Red Hat Developers (they will have already registered)
3. Need to set username
4. We need to have them authentication various OAUTH services (Github, Openshift required right now).

We'd like a page where the user can set their username (and we can communicate username constraints), and we can tell them why we are about to ask for OAUTH between services.  Pete and I discussed having this page be a "grounding" page where each OAUTH returns to so that the user can see their connections and progression.

![img_2538](https://cloud.githubusercontent.com/assets/3739227/24427168/03099afc-13d8-11e7-8665-61d9099fe0cb.jpg)

Username constraints:
* Must be less than 63 characters
* can contain lowercase letters and numbers
* can contain dashes(-) & underscores(_)
* can't start with a dash(-) or underscore(_)

**Comment by catrobson** [comment]
@jryhanyc I believe you are done with this.  Can you post your wireframes and close?

**Comment by jryhanyc** [comment]
[Final wireframes for OAUTH and Profile pages](https://redhat.invisionapp.com/share/KQB6LEHM8)
