### ISSUE TITLE
Design Thinking Workshop planning for DevSuite

### ISSUE THREAD

**Issue by catrobson** [fabric8io/fabric8-ux#367]
Dev Suite team (Dev Studio, DevSuite, CDK) have a challenge that they need more input from stakeholders outside of Dev Tools.  The team is reaching the point where they really need more input from the other business stakeholders identified above on how they can assist them with their products.

DevStudio Stakeholders:
- Bob Davis (PM)
- Dennis Golovin
- Lala Mohanty
- Jean-Francois Maury
- DV (Daniel Veillard)
- Martha Benitez Angulo

External Stakeholders we need to consider including:
- Steve Spiecher
- Ken Johnson (or assigned PM)
- Rich Sharples (or assigned PM)
- Mark Little (or assigned Eng Lead)

Pete raised the idea of Design Thinking and a workshop here, and I wanted
to get you looped in to start talking them through how it might

Verification Criteria:
* Talk with PM and ENG about design thinking session and what it consists of
* Create plan/proposal for design thinking session with the team, share with team, Pete, Catherine

**Comment by catrobson** [comment]
@muruGanesan update on status for this?

**Comment by muruGanesan** [comment]
I had multiple discussion with dev/eng team. As per today's discussion with Pete. 3 days design thinking workshop is confirmed and "QC" & "Hypothesis" features will be cover as part of this workshop. I will share the agenda and prerequisites soon.
