### ISSUE TITLE
WIREFRAMES / CODE: Remove Email and Code Inputs from Homepage

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8io/fabric8-ux#370]
According to Pete, the Email and Code inputs are no longer part of the homepage. They need to be removed and updated across all designs/code.

TBD:
- What happens when a user clicks 'Register for Developer Preview'

**Comment by mindreeper2420** [comment]
Code portion completed with PR https://github.com/openshiftio/www.openshift.io/pull/48

**Comment by jryhanyc** [comment]
[Visual designs](https://redhat.invisionapp.com/share/8FB4YEY2W) updated
