### ISSUE TITLE
CSS TASK FORCE: Planner View - Left Panel

### ISSUE THREAD

**Issue by bdellasc** [fabric8io/fabric8-ux#371]
Verification Conditions:

- Set up working sessions with @mindreeper2420 & @dgutride on aligning implementation with visuals for the left panel that were done in holistic review of the planner view.
- Post Photoshop source files before leaving on PTO so others can potentially pick up where we left off
- Post any pertinent information in InVision

**Comment by mindreeper2420** [comment]
First pass at updating the Iteration Panel through a design/code session.

![screen shot 2017-04-03 at 3 58 37 pm](https://cloud.githubusercontent.com/assets/4032718/24631065/0631b4da-188d-11e7-9d4d-f6af85420668.png)
