### ISSUE TITLE
CSS TASK FORCE: Planner View - Navigation

### ISSUE THREAD

**Issue by bdellasc** [fabric8io/fabric8-ux#376]
Verification Conditions:

- Set up working sessions with @mindreeper2420 & @dgutride on aligning implementation with visuals for the navigation that were done in holistic review of the planner view.
- Post Photoshop source files before leaving on PTO so others can potentially pick up where we left off
- Post any pertinent information in InVision

**Comment by mindreeper2420** [comment]
Updated navigation with these PRs:
- https://github.com/fabric8io/fabric8-ui/pull/703
- https://github.com/fabric8-ui/ngx-fabric8-wit/pull/72

**Comment by mindreeper2420** [comment]
Set fixed width for Spaces selector with this PR:
- https://github.com/fabric8io/fabric8-ui/pull/745
