### ISSUE TITLE
User needs to be able to create a new code project from space homepage

### ISSUE THREAD

**Issue by catrobson** [fabric8io/fabric8-ux#383]
As a user, I should be able to go through the Forge Wizard multiple times in a space to create multiple "projects".  There is no terminology agreed on for what this is called currently.  Current thinking is that this belongs on the space homepage.  This is what the "Forge" button does on the Space Wizard today.

Verification criteria:
* Add capability to initiate the wizard from the space homepage.  Update wireframes.
* Communicate updates to dev team

**Comment by muruGanesan** [comment]
I will look at this requirement and work on it

**Comment by muruGanesan** [comment]
I am assigning to me.

**Comment by catrobson** [comment]
Assigning back to me since I took this on with the other space homepage updates! :) . Updates can be seen here:  https://redhat.invisionapp.com/share/4WB1WXGK9

**Comment by muruGanesan** [comment]
@catrobson thanks Catherine.  rock star!
