### ISSUE TITLE
Add collaborators to a space

### ISSUE THREAD

**Issue by catrobson** [fabric8io/fabric8-ux#384]
From @akazakov: 
Collaborators initial version will have full access to the space. If you a collaborator you have the same permissions as the space owner. If you you are not then you can read stuff only. We don't invite collaborators. We add them or remove them. I mean a collaborator can't avoid being added to the space. Can't be notified and refuse etc. The owner can't be removed from the list of collaborators.

Verification Criteria:
* Update wireframes to include collaborator capabilities for a space
* Review with UXD team

**Comment by catrobson** [comment]
Current thinking is that we should put this into the Space settings as a second tab.

**Comment by muruGanesan** [comment]
@catrobson Do you want me to update?

**Comment by catrobson** [comment]
@muruGanesan yes please.

**Comment by muruGanesan** [comment]
https://redhat.invisionapp.com/d/main/#/console/10518262/228772655/preview

**Comment by catrobson** [comment]
@muruGanesan - oops, I should have been more specific I think.  This is the user profile, not the settings page that you modified.  The settings page can be seen here - and I think collaborators probably should be a secondary navigation item:

https://redhat.invisionapp.com/d/main/#/projects/prototypes/10321344

**Comment by catrobson** [comment]
@muruGanesan any updates on this?  @alexeykazakov - what information are you storing about a collaborator?

**Comment by alexeykazakov** [comment]
Collaborator is just a User. So the information is the same. Name, email, image, etc

**Comment by catrobson** [comment]
Perfect, thanks @alexeykazakov!

**Comment by muruGanesan** [comment]
@catrobson , @alexeykazakov, here are the screens: 
https://redhat.invisionapp.com/share/7XAIMZBBK#/230302872_Space_Setting_Collab_0

**Comment by alexeykazakov** [comment]
LGTM but I have one comment. In API there is a space owner/creator among space collaborators. The space owner has the same permissions as any collaborator but the space owner cannot be removed from the list of collaborators.
So, maybe the owner should have some special label "owner" or something.

**Comment by muruGanesan** [comment]
@alexeykazakov, Thanks for your inputs. your points are noted.

**Comment by muruGanesan** [comment]
WF completed with UX review
