### ISSUE TITLE
Upgrade fontawesome

### ISSUE THREAD

**Issue by catrobson** [fabric8io/fabric8-ux#386]
Need to upgrade to 4.7 font-awesome so that we have the full range of icons to choose from.

**Comment by mindreeper2420** [comment]
Issues submitted to both fabric8-ui and fabric8-planner to remove Font Awesome from the package dependencies for the custom patternfly-sass fork. This will allow us to upgrade Font Awesome at any time without having to upgrade PatternFly.

https://github.com/fabric8io/fabric8-ui/issues/736
https://github.com/fabric8io/fabric8-planner/issues/1619

**Comment by mindreeper2420** [comment]
this can't be upgraded at this time due to limitations with how the packages are consumed.
