### ISSUE TITLE
WIREFRAME:  Create work item - full add multiple items

### ISSUE THREAD

**Issue by catrobson** [fabric8io/fabric8-ux#399]
When I create a new work item from Full add - what is the behavior expected for entering the title and saving the work item?  It currently acts a bit odd in prod-preview.  Submitted at least one issue already on changing the title field to be in focus to start typing easier here:  https://github.com/fabric8io/fabric8-planner/issues/1741

How the save behaves should be looked at further though - if I enter something into the field and press tab, enter, or click into another field should it auto-save the name and create the work item?

**Comment by catrobson** [comment]
@mindreeper2420 would it make sense to roll this into the work you're looking at?

**Comment by mindreeper2420** [comment]
@catrobson I think so. I can extend the work from the Quick Add where I looked into having it be in the Detail Panel.

**Comment by mindreeper2420** [comment]
Wireframe Design: https://redhat.invisionapp.com/share/WPBVEZF7C
