### ISSUE TITLE
WIREFRAME:  Planner view behavior [2]

### ISSUE THREAD

**Issue by catrobson** [fabric8io/fabric8-ux#401]
Consider the view behavior for Planner.  How can we go from separate pages to "views" that switch the user between hierarchy, list, and board without losing the context of their iteration and filter criteria?

VCs:
* Wireframes captured in InVision for design changes
* Wireframes reviewed with UXD
* Spin off a number of smaller stories that have a more targeted focus for the different UI pieces.

History:
Prior to summit, it was suggested that we should have a "Show:  Closed, Removed" in the filter toolbar to show closed and removed work items.  Then Michael K also added functionality to be able to show a flat list vs. a hierarchical list.  Reconciliation after these last minute additions is needed.

**Comment by catrobson** [comment]
Issue with the Show behavior we discussed last week:  https://github.com/fabric8io/fabric8-planner/issues/1621

**Comment by bdellasc** [comment]
Started work on Sketch wireframes. Still need to document the various situations we could find ourselves in when switching between the various Planner views.

**Comment by bdellasc** [comment]
I will schedule a meeting RE: talking through the various interlocking/overlapping aspects of the Planner view behavior. This discussion should result in a list (organized by priority for the MVP, where applicable)

**Comment by bdellasc** [comment]
Scheduled Meeting for May 30.

**Comment by bdellasc** [comment]
InVision Sketches [posted here](https://redhat.invisionapp.com/share/UVBV070CE)

**Comment by bdellasc** [comment]
We met on May 30 - here are the [meeting notes](https://docs.google.com/a/redhat.com/document/d/1fLFEtSIC42Ck27QTzGj1wCpNJgogFZw5KmT69jzRPjE/edit?usp=sharing)

As we sort out next steps, we'll form some stories based on what we discussed.
