### ISSUE TITLE
HOMEPAGE:  My Work Items widget empty states

### ISSUE THREAD

**Issue by catrobson** [fabric8io/fabric8-ux#402]
For this widget - we need multiple empty states:
![image](https://cloud.githubusercontent.com/assets/3739227/25398937/b88f6282-29bb-11e7-962a-77caa63f7950.png)

Empty state 1:  There are no spaces.  In that case I think the space dropdown should not show, and we should have an empty state that describes the need to create a space (similar to current text shown).

Empty state 2:  You have selected a space from the dropdown, but the space has no work items assigned to you.  There should be a different empty state in this situation that shows that you have no work items assigned to you.

Need to design these and send them to Dan L.

**Comment by catrobson** [comment]
@jryhanyc - if you get a chance can you check this out?

**Comment by jryhanyc** [comment]
@catrobson will do

**Comment by jryhanyc** [comment]
@catrobson [Two empty states](https://redhat.invisionapp.com/share/K9BG3UHPR#/230703402_A-0300_SpaceNoWI) are ready to review

**Comment by catrobson** [comment]
@mindreeper2420 - hope to connect with you on this when you return.
