### ISSUE TITLE
VISUAL:  OpenShift.io github logo

### ISSUE THREAD

**Issue by catrobson** [fabric8io/fabric8-ux#404]
A square openshift.io logo for the github account.

Where will it go?
https://github.com/openshiftio
Auth pages for accepting OpenShift.io authentication on things like launch.openshift.io.

Example of how OpenShift did this:
https://github.com/openshift

- Source files here: http://design.jboss.org/openshiftio/
- 2 resolutions: 72 & 144
- 500x500px dimensions

**Comment by bdellasc** [comment]
Sent Libby Levi in brand some images and she approved them.
There are two 500px x 500px versions: a 72ppi (@1x) and 144ppi (@2x for high density displays)

![1x_osio_500px](https://cloud.githubusercontent.com/assets/17882357/25498689/009dfc18-2b57-11e7-90a6-f0ca2d06a0eb.png)
<img width="500" alt="2x_osio_500px" src="https://cloud.githubusercontent.com/assets/17882357/25498690/009ff3e2-2b57-11e7-8d45-812fac107ff5.png">

**Comment by catrobson** [comment]
@ALRubringer - red hat square logos here for you

**Comment by ALRubinger** [comment]
Thank you, all!

Updated the OAuth applications we have in the org to use this (users will see it when they are asked to approve access)
![screenshot5](https://cloud.githubusercontent.com/assets/199891/25567492/fe12c61e-2dbc-11e7-9b8e-d6834a173ac5.png)
