### ISSUE TITLE
Overview: Layout/Design/CSS Fixes

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8io/fabric8-ux#405]
This issue is for tracking the various areas that will be fixed throughout the product. As part of this work, both Planner and Platform will be touched.

All areas are to be tested on a 1280px wide screen for presentation purposes.

**Board View**
- [x] card highlights
- [x] truncation
- [x] column background colors
- [x] column borders
- [x] assigned user icon sizes
- [x] unassigned user icon sizes
- [x] tooltip positioning over user/unassigned icons
- [x] remove column highlight when drag/drop card - match designs
~~- [ ] change color of card on drag/drop - match designs~~
~~- [ ] fix highlights for target dropdown box (change to blue line) - match designs~~
_cannot match designs due to library limitations-converted to an opaque box_
- [x] Quick Add to match visuals

**Iteration Panel**

- [ ] tooltip activation
- [ ] bottom of titles cut off

**List View**

**Quick Add of Work Item**
- [x] change type picker to button
- [x] fix jumping of quick add bar on selection

**Full Add of Work Item**
- [x] remove description placeholders
- [x] remove truncation ellipsis
- [x] fix height issues of background

**Home Dashboard**

- [x] Change background color to match color of Board columns
- [x] My Work Items card needs alignment fix
- [x] Remove 'Create XYZ' from before the '+' in Card headers

**Spaces Dashboard**

- [x] Change background color to match color of Board columns
- [x] Remove 'Create XYZ' from before the '+' in Card headers
- [x] Codebases card needs alignment fix
- [x] My Work Items card needs alignment fix
- [x] Stack Reports needs proper empty state to match other cards

**Detail Panel**

- [ ] Assign User dropdown
- [ ] Area dropdown
- [ ] Iteration Dropdown
- [ ] Status dropdown (cursor is incorrect)

**Create Space Wizard**

- [ ] Investigate using medium size modal versus large modal

**Comment by catrobson** [comment]
![image](https://cloud.githubusercontent.com/assets/3739227/25435599/8174c58c-2a5e-11e7-9eca-57f605821a5b.png)
- Can we do hover pop-ups on the icons in these cards on the account homepage and space homepage so the user can get a sense of what the icons are?

**Comment by mindreeper2420** [comment]
**Full Add**
![screen shot 2017-04-26 at 3 45 44 pm](https://cloud.githubusercontent.com/assets/4032718/25453594/8794eeb8-2a97-11e7-896c-e9742d168cdb.png)

**Quick Add**
![screen shot 2017-04-26 at 3 45 53 pm](https://cloud.githubusercontent.com/assets/4032718/25453604/8f869a40-2a97-11e7-8e9e-ae033e750fb1.png)

**Cards in Column - Board View**
![screen shot 2017-04-26 at 3 46 06 pm](https://cloud.githubusercontent.com/assets/4032718/25453611/9c01bd72-2a97-11e7-866f-3a7ec402e640.png)

**Selected Card in Column - Board View**
![screen shot 2017-04-26 at 3 46 18 pm](https://cloud.githubusercontent.com/assets/4032718/25453622/a5e17508-2a97-11e7-8924-6681f231ea61.png)

**Comment by Essjaysee** [comment]
@mindreeper2420 The arrow on the drop-down for the icons in quick add is pointing up...should be down, right?  Or am I overtired?  Or both?

**Comment by mindreeper2420** [comment]
@Essjaysee Bootstrap uses the up arrow for drop-ups and PatternFly references that, so I went down that rabbit hole :-)

**Comment by catrobson** [comment]
@mindreeper2420 looks like the text on the cards is still justified instead of left aligned here?

**Comment by mindreeper2420** [comment]
@catrobson yes, that is an issue with how the truncation is handled for multi-line items. Once Sukhvir's PR is merged with various fixes, I'm going to take another look at it.

**Comment by mindreeper2420** [comment]
**Home Dashboard**
<img width="1920" alt="screen shot 2017-04-26 at 9 17 31 pm" src="https://cloud.githubusercontent.com/assets/4032718/25463662/d0ad81e0-2ac5-11e7-9cc0-f3333c9e7d8d.png">

**Comment by mindreeper2420** [comment]
**Quick Add - Board View**
<img width="362" alt="screen shot 2017-04-26 at 9 19 08 pm" src="https://cloud.githubusercontent.com/assets/4032718/25463703/059daccc-2ac6-11e7-9188-feac08586815.png">

**Comment by mindreeper2420** [comment]
**Space Dashboard**
<img width="1920" alt="screen shot 2017-04-26 at 9 44 11 pm" src="https://cloud.githubusercontent.com/assets/4032718/25464288/8f87e0ee-2ac9-11e7-8d6d-2c336a2dc45c.png">

**Comment by catrobson** [comment]
Space dashboard - way to decrease the space between top row and second row to be same as space between cards?

**Comment by mindreeper2420** [comment]
Initial PR for Space and Home dashboards filed here: https://github.com/fabric8io/fabric8-ui/pull/1129

**Comment by mindreeper2420** [comment]
Updated Space Dashboard:
<img width="1920" alt="screen shot 2017-04-26 at 10 02 41 pm" src="https://cloud.githubusercontent.com/assets/4032718/25464765/1d1aefa8-2acc-11e7-8ca2-a157d1e80e8c.png">

**Comment by mindreeper2420** [comment]
Truncation of the list items inside of the cards were broken on 1280px wide screen, but have been remedied with PR https://github.com/fabric8io/fabric8-ui/pull/1144.

**Comment by mindreeper2420** [comment]
Planner update, which includes fixes to the Board view and other visual improvements, can be found here: https://github.com/fabric8io/fabric8-planner/pull/1798.
