### ISSUE TITLE
WIREFRAMES:  Board view support of multiple WI types

### ISSUE THREAD

**Issue by catrobson** [fabric8io/fabric8-ux#409]
The board view only supports one work item type currently as the status columns might change between work item types displayed.

VCs:
* Get input on expectations from PM around the board view
* Brainstorm board interaction options for supporting multiple work item types
* Review options with Dev, PM, UX for a decision on what would make the most sense as the next step for board view improvement.  Document new designs as wireframes in InVision.

**Comment by catrobson** [comment]
Can we make this highest priority for next sprint?  We need to move this forward.  We can re-assign if you're busy prepping for the design thinking sessions!

**Comment by muruGanesan** [comment]
I created first-cut wireframe for review: 
https://redhat.invisionapp.com/d/main/#/projects/prototypes/11152694
