### ISSUE TITLE
UX REVIEW & WIREFRAME:  Collaborator improvements

### ISSUE THREAD

**Issue by catrobson** [fabric8io/fabric8-ux#410]
An initial version of collaborators has been added into the platform UI.  Review what exists, and design any improvements that we should consider short term that will:

* Make it easier to find people to add as collaborators
* Make it easier to manage collaborators
* Define what being a collaborator will provide to me for permissions across the system
* Make it more intuitive what being a collaborator will do to users

VCs:
* Wireframes, documentation, interaction specs captured around collaborators
* Review with UXD Team

**Comment by catrobson** [comment]
From the UX workshop:

- How to help users filter through the (soon to be) huge list of collaborators?
- Privacy issues by exposing the giant list?
- What are the permissions/privileges given to collaborators vs. general public?
- Explore allowing some collaborators to be admin so that they can add other collaborators to the space

**Comment by muruGanesan** [comment]
Since, I worked on the collaborator page, I will work on this enhancement.

**Comment by maxandersen** [comment]
@catrobson Isn't all the issues you mention about collaborators one of the primary reasons why full team management is needed ?

also, afaik Collaborators are limited to the notion of collaborators found in openshift internal model which does not map well to what we need on something like openshift.io if we are targeting multiple openshift deployments.

**Comment by muruGanesan** [comment]
@maxandersen, I am sorry to say that, I unable to understand your comment/query. Could you please help me to understand your query? So that, it will help me to resign the "collaborator" module better.

**Comment by muruGanesan** [comment]
UX review is in progress:
https://redhat.invisionapp.com/d/main/#/projects/prototypes/10321344.
I will close it by tomorrow.

**Comment by catrobson** [comment]
@joshuawilson, @dgutride can you take a look at the wireframes updates underway and see if you have any comments or concerns beyond what we already have in InVision?
