### ISSUE TITLE
PROCESS:  UXD to Dev Process

### ISSUE THREAD

**Issue by catrobson** [fabric8io/fabric8-ux#415]
UXD team interaction design → visual design → development process

What can we do better?

ASK: Could folks on the UXD team add some comments to this item to start kicking around ideas for this topic?

**Comment by bdellasc** [comment]
I'd meet with Dana, Dan and Joshua RE: easing the frustrations/streamlining getting the visuals implemented on featured and UX Designs.

**Comment by mindreeper2420** [comment]
I would like to see us provide HTML/CSS to the dev team, especially in regards to the visual design specs. This would cut down on the visual design team having to provide specs, and relying on our tools to provide spacing/colors/effects (i.e. Zeplin).

As we move towards the introduction of mobile designs and motion, having direct code/specs to provide to the development team will help to cut back on the back/forth between the groups and speed up the overall process.

**Comment by jryhanyc** [comment]
Are there other tools we could be using instead of Photoshop to create high-fidelity mockups? I know Adobe Muse was supposed to be able to output code...

**Comment by sdash-redhat** [comment]
Some initial thoughts on the gaps in the existing process and the process related suggestion  I have noted down here - https://docs.google.com/presentation/d/1ByPJy0dVN4b2lccWg6tANnzkLlQcGVJspH5Aawv-hlQ/edit#slide=id.g1e123f28d1_0_117

**Comment by sdash-redhat** [comment]
Apart from the tools we use, there are certain process elements which which should be re-looked at .. 
For example the whole process flows from the system engineering perspective and mostly the epic created from the use-case perspective - mostly the epics are drilling down from the PDD and are defining the user stories. I believe that is where we need to re look at . The use-case based PDD driven approach to define the stories is though good for the agile approach , it is mostly needs refine to be a UCSD (User Centred System Design ) . Basically once we have the highlevel product vision is ready, the stories should be created from user goals, and then mapped to the high-level product vision via the Information Architecture. By this time the user segmentation should have been done, based on the persona sets that trigger the user goals.
