### ISSUE TITLE
PROCESS: Planning & user scenario driven development

### ISSUE THREAD

**Issue by catrobson** [fabric8io/fabric8-ux#416]
Planning process - moving from PDD to user scenario driven development.  Help the dev team focus on user-centric development.

How would you suggest we improve this process?

ASK: Could folks on the UXD team add some comments to this item to start kicking around ideas for this topic?

**Comment by jryhanyc** [comment]
Do we have examples of documentation or guides they could reference to see what following user scenario driven development is like? I know some kind of quick tips or a guide would be helpful for me when meeting with devs.

**Comment by Essjaysee** [comment]
This is part of the audience/personas thing, but figuring out ways to interject the personas into everything we create and figuring out a non-obnoxious way to talk about it frequently might be good.

**Comment by sdash-redhat** [comment]
Some initial thoughts on the gaps in the existing process and the process related suggestion I have noted down here - https://docs.google.com/presentation/d/1ByPJy0dVN4b2lccWg6tANnzkLlQcGVJspH5Aawv-hlQ/edit#slide=id.g1e123f28d1_0_117

**Comment by sdash-redhat** [comment]
Apart from the tools we use, there are certain process elements which which should be re-looked at ..
For example the whole process flows from the system engineering perspective and mostly the epic created from the use-case perspective - mostly the epics are drilling down from the PDD and are defining the user stories. I believe that is where we need to re look at . The use-case based PDD driven approach to define the stories is though good for the agile approach , it is mostly needs refine to be a UCSD (User Centred System Design ) . Basically once we have the highlevel product vision is ready, the stories should be created from user goals, and then mapped to the high-level product vision via the Information Architecture. By this time the user segmentation should have been done, based on the persona sets that trigger the user goals.
