### ISSUE TITLE
WIREFRAME: Collaborators refinement

### ISSUE THREAD

**Issue by Essjaysee** [fabric8io/fabric8-ux#422]
Iterate on the interaction design for collaborators.

From the UX workshop:
- How to help users filter through the (soon to be) huge list of collaborators?  
- Privacy issues by exposing the giant list?
- What are the permissions/privileges given to collaborators vs. general public?
- Explore allowing some collaborators to be admin so that they can add other collaborators to the space

**Comment by catrobson** [comment]
Closing this story and moving items into #410
