### ISSUE TITLE
WIREFRAMES: Quick add refinement

### ISSUE THREAD

**Issue by Essjaysee** [fabric8io/fabric8-ux#424]
From UX workshop:
- Check that when an WI is added from a context that everything is updated accordingly.  For example, if you are on an iteration and do quick add, that the WI is automatically associated with that selected iteration
- Are applied filters a context we should consider vis-a-vis quick add?
- Explore ways to make sure it's clear to the user the context that they are quick-adding to
- Is it possible to create something that wouldn't appear based on your context?

**Comment by mindreeper2420** [comment]
First Pass of wireframes: https://redhat.invisionapp.com/share/ZNBQM11YC
