### ISSUE TITLE
VISUAL DESIGN:  Object View page visual template [3]

### ISSUE THREAD

**Issue by catrobson** [fabric8io/fabric8-ux#425]
We have several list view pages that need a visual styling template to follow.

I think the standard components to consider are:
1. A description since the tab name isn't enough in our cases where we want to help the user understand the system and what they are seeing.
2. The toolbar that allows for filtering and actions
3. Add object
4. The view itself

![image](https://cloud.githubusercontent.com/assets/3739227/26003140/d9d1432e-36ff-11e7-98e4-54da38318ccf.png)

I think we can rely on PatternFly for the toolbar and list view specs, but how this sits in the larger framework of our application at the top is where I would like to see us come up with a standard design we all agree on.

The description in this case would take up some pretty important real estate at the top, so if you have other ideas or suggestions on how you might want to organize these views that would be great.  We could consider things like info tips to help with this instead for instance.

Pages that follow this today:
https://redhat.invisionapp.com/share/7XAIMZBBK - areas and collaborators
These have a title area today in the wireframes as well as add.  Should standardize to title, description, add, toolbar for search/filter.

https://redhat.invisionapp.com/d/main#/console/10565498/224946838/preview - pipelines and environments (environments not yet implemented)
These don't have a title, but should gain a title and description above the toolbar

https://redhat.invisionapp.com/share/FXACSF1AP#/230504758_Codebases - codebases
Doesn't have a title and description at top, should add these above toolbar.

**Comment by muruGanesan** [comment]
@catrobson, I am discussing with Sunil on this backlog... it looks like, we need to standardize the controls and data visualization (with reference to PF) - am I right? More of Modular approach like PF. Please let us know your thoughts to move forward.

**Comment by sunilmalagi** [comment]
![withfilter](https://cloud.githubusercontent.com/assets/25147584/26347739/1b378780-3fc8-11e7-8992-f4768045ecc9.png)
![withoutfilter](https://cloud.githubusercontent.com/assets/25147584/26347737/1ab7a984-3fc8-11e7-961c-b09a1858a686.png)
@catrobson here is the rough idea of showing page title, filter & add element, which are already there and I need to understand what else is missing and what I am suppose to crack here is I would like to know.  5-10 minutes call with you might help me in understanding the issue.

**Comment by sunilmalagi** [comment]
@catrobson Please share screens captures as we discussed in our last meeting, as I am not able to get those screens from my login credential. Thank you

**Comment by catrobson** [comment]
Closing this issue as this is now outdated, and we'll address this as we move through platform improvements.
