### ISSUE TITLE
HTML/CSS Code Guidelines

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8io/fabric8-ux#429]
Not sure where to put this, but I'd like to have a conversation around HTML/CSS coding guidelines before the product is opened up to the public. I'll leave the javascript up to others :-)

I'd like to follow the guidelines as described here: http://codeguide.co.

> Every line of code should appear to be written by a single person, no matter the number of contributors.

@joshuawilson @michaelkleinhenz @pmuir @SMahil @catrobson

**Comment by mindreeper2420** [comment]
IMO, not only can we update what we have to ensure that we follow the idea of having the code appear as if it was written by a single person, but establish guidelines/rules for all contributors.

**Comment by SMahil** [comment]
: +1

**Comment by mindreeper2420** [comment]
I've refreshed the CSS for OpenShift/OpenShift.io with these guidelines (https://github.com/openshiftio/openshift.io). I'd like to start on fabric8-ui first, and then move to fabric8-planner.

**Comment by mindreeper2420** [comment]
PRs submitted to the following repos:
- runtime-console: https://github.com/fabric8-ui/fabric8-runtime-console/pull/473
- ngx-widgets: https://github.com/fabric8-ui/ngx-widgets/pull/79
- fabric8-ui: https://github.com/fabric8io/fabric8-ui/pull/1308

**Comment by mindreeper2420** [comment]
@SMahil would you be up for handling the Planner refactor of this? You have the most knowledge of that system and can work hand-in-hand with the dev team.

**Comment by SMahil** [comment]
sure @mindreeper2420

**Comment by mindreeper2420** [comment]
Planner Work:

- [Issue](https://github.com/fabric8io/fabric8-planner/issues/1880)
- [Pull Request](https://github.com/fabric8io/fabric8-planner/pull/1892)
