### ISSUE TITLE
WIREFRAME:  Change work item type (quick add scenario)

### ISSUE THREAD

**Issue by catrobson** [fabric8io/fabric8-ux#438]
Consider if and how the user should have the ability to change work item type after quick add & before further information is filled out.

Users cannot change work item types after the work item has a significant amount of information in it, but should we enable users to change the work item type when they do a quick add and realize they have added a work item with the wrong type?

**Comment by joshuawilson** [comment]
I think it would be good to have a user flow that allows for that. Maybe timed or only on initial edit.
You should know that Todd thinks that it should not be changed and a new work item should be created and linked to it.

**Comment by mindreeper2420** [comment]
I created a few options for this, as part of this wireframe: https://redhat.invisionapp.com/share/ZNBQM11YC. 

There are two ideas:
- Keeping the current Quick Add mechanism, but adding an "UNDO" feature, which has to be completed within the 8 seconds that a toast notification is available (Screen 5).

- Converting all actions for creating a new Work Item to use the Detail Panel. This would require the user to "Commit" their new Work Item (replace the checkmark with 'commit'). Before a user "commits" their new Work Item, they can change the Type. After clicking "commit", the toast notification appears, giving them 8 seconds to undo. This unifies the entry points for creating Work Items, but still, allows a user to quickly add items (screens 10 & 11).
