### ISSUE TITLE
QUESTION: Add Design List To OSIO?

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8io/fabric8-ux#446]
Can we move the design list from https://fabric8io.github.io/fabric8-ux/invision-links.html to an OSIO Space?

**Comment by mindreeper2420** [comment]
<img width="1920" alt="screen shot 2017-05-24 at 1 18 58 pm" src="https://cloud.githubusercontent.com/assets/4032718/26416364/9d4bd17a-4083-11e7-9b2f-d737b67e7585.png">

**Comment by mindreeper2420** [comment]
![designlist](https://cloud.githubusercontent.com/assets/4032718/26418493/6b4e5f60-408a-11e7-9a92-047b8ce9b8b2.png)

**Comment by catrobson** [comment]
Not really for today.  We'll want to think about how the design process fits into OSIO eventually, but not a focus item for right now!

**Comment by mindreeper2420** [comment]
sounds good!
