### ISSUE TITLE
WIREFRAMES: Full-page work item design [3]

### ISSUE THREAD

**Issue by Essjaysee** [fabric8io/fabric8-ux#449]
Revisit the designs for showing work item detail as a full page.  Consider:

- How to show the context (space, area, iteration, etc.)
- How to get the user back to the planner easily once they're done with the work item

VC:
- create follow-up wireframe stories for additional drafts
- review with Product Team

**Comment by mindreeper2420** [comment]
Wireframe w/animation here: https://redhat.invisionapp.com/share/4NBW9EM2H
