### ISSUE TITLE
DISCOVERY: Explore 2-panels-at-a-time to reduce clutter [5]

### ISSUE THREAD

**Issue by Essjaysee** [fabric8io/fabric8-ux#450]
Does it make sense to show the WI detail panel AND the work item list AND the iteration panel?  Explore ways to show just 2 at a time (desktop) or 1 at a time (mobile).

VC:
- Post any pictures and/or discussions around discovery tasks
- Show Product Team results and review
- Create follow-up wireframe stories

**Comment by mindreeper2420** [comment]
@essjaysee As I started this for the quick add discovery, can I grab this one?
