### ISSUE TITLE
VISUAL DESIGN: Community branding [3]

### ISSUE THREAD

**Issue by catrobson** [fabric8io/fabric8-ux#456]
Specify changes for community build in branding, and provide to James Rawlings and Joshua Wilson.   Fabric8 backgrounds and logos can be found here http://design.jboss.org/fabric8/

**Comment by jryhanyc** [comment]
[Designs for review](https://redhat.invisionapp.com/d/main/#/projects/prototypes/11182786)

**Comment by rawlingsj** [comment]
@catrobson / @jryhanyc can myself @jstrachan and @rajdavies get access to the invision project to look at the designs please?

**Comment by catrobson** [comment]
You can see them with this link @rawlingsj  - https://redhat.invisionapp.com/share/N4C3P1PUW#/screens/236499597

**Comment by rawlingsj** [comment]
Thanks @catrobson this was exactly what I was after and the designs look good.  Do we know what the next steps are?  Do these still need to be approved or can we look at getting the community docker image built with these?

**Comment by catrobson** [comment]
You can go ahead and start building these into the community image.  Let us know if you need any specific assets as you go.

**Comment by rawlingsj** [comment]
Ok perfect - it looks great BTW, thanks for this.

**Comment by catrobson** [comment]
Closing as design work is complete.
