### ISSUE TITLE
Wireframe: Simple Filter - Version #1

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8io/fabric8-ux#55]
As a user of ALM, I should be able to find a work item by it's title or id (and maybe description), so that I can easily access any work item in the system and get the URL.

The designs listed cover the following:
* [A Simple Filter via Text Input and Selection](https://redhat.invisionapp.com/share/T79EF22F9#/206310850_AssignUser_-_000_-Basic-)
* [Quick Filter via 'Assign to Me' criteria (user must be logged in)](https://redhat.invisionapp.com/share/T79EF22F9#/208756097_Fixed_Filter_-_000)

JIRA Issue: https://patternfly.atlassian.net/browse/RHUAP-173

**Comment by sanbornsen** [comment]
Why do we have the **+ New** in that bar?
