### ISSUE TITLE
UX for dialog-based creation of new work Items

### ISSUE THREAD

**Issue by nimishamukherjee** [fabric8io/fabric8-ux#56]
Define the user experience for dialog-based creation of new work Items. The details can be accessed at - https://github.com/almighty/almighty-core/issues/501.
We will be working on the UI for this story in our next sprint (123 - Nov 30 to Dec 20)

**Comment by mindreeper2420** [comment]
@nimishamukherjee @michaelkleinhenz @almighty/uxd The dialog based creation should be a 1-1 match to the Details View, just as a model. That can be the first pass for this and will be iterated on in  the future.

See this PatternFly example for forms within modals: http://www.patternfly.org/pattern-library/forms-and-controls/forms/

**Comment by nimishamukherjee** [comment]
Thanks @mindreeper2420 we will use the PatternFly modal to design the dialog based work item creation.
@mindreeper2420 @Mgranfie we still need your input on the mechanism to trigger the dialog based work item creation. Example, do we click a "Add Work Item in detail" button?

**Comment by mindreeper2420** [comment]
@nimishamukherjee see @Mgranfie 's comments on almighty/almighty-core#501.
