### ISSUE TITLE
Display work item creation date / timestamp

### ISSUE THREAD

**Issue by nimishamukherjee** [fabric8io/fabric8-ux#57]
We need to display the work item creation date / timestamp on new work Items - https://github.com/almighty/almighty-core/issues/499.

Will the date/timestamp be displayed on the work item list?

We will be working on the UI (https://github.com/almighty/almighty-ui/issues/350) for this story in our next sprint (123 - Nov 30 to Dec 20)

**Comment by mindreeper2420** [comment]
@nimishamukherjee There will be no additional information added to the Work Item List, other than what is currently in the designs.

Additionally, we do not have designs for showing the date / time stamps on New Work Items. @Mgranfie is this a requirement of the PDD or in your IA? If not, I feel we should leave that out of the Details View - possibly something for inclusion in the history.

**Comment by Mgranfie** [comment]
@nimishamukherjee @mindreeper2420 We do not have this in the UI to date, but should. I will put this as a story in for our next sprint or two.

**Comment by nimishamukherjee** [comment]
@Mgranfie Another input we would need would be the display format. Do we display the information like
Creation time : 3 days ago
and on hover display the exact date and time?

**Comment by Mgranfie** [comment]
@nimishamukherjee @bdellasc is working on this now, looping him in here.
