### ISSUE TITLE
Display of story creator (User) on work Items

### ISSUE THREAD

**Issue by nimishamukherjee** [fabric8io/fabric8-ux#58]
Define the user experience around display of story creator (User) on work Items - https://github.com/almighty/almighty-core/issues/500

Will the creator be displayed on the work item list?

We will be working on the UI (https://github.com/almighty/almighty-ui/issues/351) for this story in our next sprint (123 - Nov 30 to Dec 20)

**Comment by mindreeper2420** [comment]
@nimishamukherjee here is the design for displaying the creator on Work Item Details:

https://redhat.invisionapp.com/share/5R9I5ERST#/201494068_A-0500

Currently, we do not display the Creator in the List View. There are no requirements for that at this time.
