### ISSUE TITLE
Linking Work Items by Description

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8io/fabric8-ux#61]
Currently, when linking work items together, you are given the option to search via a text string. This allows for searching strings within the Description field, causing unreadable results to display in the drop-down list. As a solution to this problem, the results from a description should display as follows:

![screen shot 2016-12-01 at 12 47 09 pm](https://cloud.githubusercontent.com/assets/4032718/20805820/51336fb4-b7c6-11e6-873d-f86ca3f39aed.png)

Possible Solution:
1. Search for 'dr'
2. Result: "Description from PTNFLY-001: 'the **dr**ive dictates the speed of the machine...'"
    - 'dr' in 'drive' is highlighted to show that as a matching result
    - the ellipsis is used to keep the result on one line, rather than showing the entire paragraph that contains the searched letters of 'dr'.

Thoughts?

**Comment by bdellasc** [comment]
Agreed. Limiting the result to one line absolutely makes sense, especially when many results can be returned.
