### ISSUE TITLE
WIREFRAMES 1: Order of Execution

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8io/fabric8-ux#62]
JIRA Issue: https://patternfly.atlassian.net/browse/RHUAP-545

InVision Wireframes: https://redhat.invisionapp.com/share/5D9JPDJXE

**Comment by DhritiShikhar** [comment]
@mindreeper2420 shouldnot "Move Up" and "Move down" for a single item appear in the kebob menu itself?

**Comment by mindreeper2420** [comment]
@DhritiShikhar no, as the kabob is only for a small subset of items. Following established UXD patterns, the single movements are located in an action button. The wireframe has been updated with a proper move workflow.

**Comment by nimishamukherjee** [comment]
@almighty/uxd how would Move to Top and Move to Bottom behave with pagination (infinite scroll)?
I can think of two options:
1. Consider the visible screen only - if the page displays 10 items at a time move top/bottom will move the selected item to the top or bottom of these 10 items?
2. Consider all the work items - if there are 1000 work items, move top/bottom will move the selected work item to the top/bottom of these 1000 items.

**Comment by mindreeper2420** [comment]
@nimishamukherjee I added this to the wireframe comment that you left (thanks!), but I'll add my reponse here as well.

The Move to Top, Move to Bottom action would move the item to the top/bottom of the visible list - if 100 items have been loaded due to scrolling (or screen size), then the items will move to the top/bottom of that visible/loaded list.

**Comment by nimishamukherjee** [comment]
Thanks @mindreeper2420

**Comment by mindreeper2420** [comment]
@DhritiShikhar this is explained on Step 5 (screen 6) of the wireframe.
