### ISSUE TITLE
ALM - VISUALS: Define Draft of Default Icons for Work Items

### ISSUE THREAD

**Issue by bdellasc** [fabric8io/fabric8-ux#64]
Corresponding JIRA stories [here](https://patternfly.atlassian.net/browse/RHUAP-406): 

Per the PDD:

"**Work Items**
Each work item herein – a Scenario, a Value Proposition, an Experience, a Fundamental or a Remove Customer Dissatisfier", but there's no mention of: Feature, User Story, Bug or Epic.

My impression for status types was: New, Not started, In Progress & Done. However in the PDD, I'm seeing reference to: New, Active, Blocked, Unverified, Closed, Fixed.

@qodfathr, @michaelkleinhenz, @michaelvirgil, @maxandersen In order to figure out appropriate corresponding icons, I'd need to know the actual current lists for:
- work item types (+ definitions)
- states (+definitions) 

Thanks!

**Comment by qodfathr** [comment]
The work flows are not predefined. The states will change -- and eventually be end-user defined. As such, I do not recommend any icons for states.

Same goes for work item types, although in this case I'd say it's reasonable for WITs to have optional icons as part of the definition. The initial set of WITs will be in flux for a few months, although you'll start to see proposals soon. Feel free to work against those. Honestly, a set of 6-10 icons probably reasonably covers all common use cases.

**Comment by bdellasc** [comment]
OK, for purposes of the demo, I'll just leave these listed here, then we can circle back and revisit if need be. Thanks!

**Comment by bdellasc** [comment]
There is a new story to continue this work.
