### ISSUE TITLE
WIREFRAMES - Comments

### ISSUE THREAD

**Issue by Mgranfie** [fabric8io/fabric8-ux#65]
As a user of the ALM Product, I should be able to add, edit and remove a comment for a Work Item, so that I can have and maintain conversations on the work item, without having to use another product.

JIRA:
https://patternfly.atlassian.net/browse/RHUAP-553

InVision:
https://redhat.invisionapp.com/share/Q6AAQVO8X
https://redhat.invisionapp.com/share/N3AAHZYUP

Git related stories:
https://github.com/almighty/almighty-core/issues/316
https://github.com/almighty/almighty-core/issues/348
https://github.com/almighty/almighty-core/issues/349
https://github.com/almighty/almighty-core/issues/350
https://github.com/almighty/almighty-core/issues/351

**Comment by nimishamukherjee** [comment]
@Mgranfie can we use https://redhat.invisionapp.com/share/6E9OIX4YB#/screens/211288921 as the wireframe for Comments on a Work Item?

**Comment by Mgranfie** [comment]
Yes this is the correct set of wireframes

On Wed, Jan 11, 2017 at 3:33 AM, Nimisha Mukherjee <notifications@github.com
