### ISSUE TITLE
ALM - VISUALS: Iterations

### ISSUE THREAD

**Issue by bdellasc** [fabric8io/fabric8-ux#66]
Iteration stories:
1. [Iterations Visuals](https://patternfly.atlassian.net/browse/RHUAP-557)
2. [Add Date Range & Specs to Iterations Visuals](https://patternfly.atlassian.net/browse/RHUAP-568)

Completed the visual design & specs for current Iteration functionality, [posted to InVision](https://redhat.invisionapp.com/share/FR9R8G6B9).

Core Issue: https://github.com/almighty/almighty-core/issues/409

**Comment by bdellasc** [comment]
@joshuawilson @aslakknutsen @maxandersen @michaelkleinhenz

**Comment by vikram-raj** [comment]
@bdellasc Is iteration pan have slide in and slide out functionality or it is always visible?

**Comment by bdellasc** [comment]
@vikram-raj _ believe the panel is always visible. @Essjaysee, since you're the interaction designer who [posted the wireframes in InVision](https://redhat.invisionapp.com/share/KA9CAYL7M), can you confirm that is is always visible? I looked through the document, but didn't see any mention of this.

**Comment by Essjaysee** [comment]
@vikram-raj Yes, the panel will always be visible.  I'll make a note in the wireframes as well.  Thanks!

**Comment by vikram-raj** [comment]
@bdellasc @Essjaysee Thank you.

**Comment by sanbornsen** [comment]
@Essjaysee Thanks for clarification. So far we have been thinking it's gonna be a slid out with shrinking the rest of the screen. 
@nimishamukherjee @joshuawilson @michaelkleinhenz please take a note.

**Comment by joshuawilson** [comment]
@Essjaysee I confirmed with @qodfathr that the Iterations panel will also be on the Board view. Does that change your thoughts on making it a slide out? How does this panel work in a Mobile view?

**Comment by qodfathr** [comment]
Note that drag-and-drop a work item onto an iteration is expected to be a VERY common activity, which would seem to imply that the iteration list should always be visible. Also, switching between iterations and backlog views is also very common -- another suggestion that always visible makes sense.

**Comment by bdellasc** [comment]
Adding links to wireframes & visuals (for future/continuing reference):
[Wireframes Flow](https://redhat.invisionapp.com/share/KA9CAYL7M)
[Visuals Flow](https://redhat.invisionapp.com/share/FR9R8G6B9)
