### ISSUE TITLE
Visual design for Dialog-based creation of new Work Items

### ISSUE THREAD

**Issue by nimishamukherjee** [fabric8io/fabric8-ux#67]
We need the visual designs for dialogue-based creation of new work items.

**Comment by bdellasc** [comment]
@nimishamukherjee - thanks for the heads up! I believe we already have a JIRA story for this issue. I'll verify and then link to it here so it can be tracked once work begins. 

My typical process is:  
- We write up the story in our JIRA backlog, get it pointed
- I create the issue here in Git, then link to the story I wrote in JIRA once work begins on that story.

I've been trying to only add these stories here until work actually begins on the issue. Otherwise, it gets too chaotic and hard for me to match things up.

**Comment by nimishamukherjee** [comment]
Thanks for the update @bdellasc . Will wait for your update.

**Comment by bdellasc** [comment]
@nimishamukherjee - just to be clear, the visual design work will not occur until after shutdown. I hope to get the JIRA story linked to this one later today.

**Comment by nimishamukherjee** [comment]
Understood @bdellasc.  Our sprint ends Jan 10th. Would we get the visual design before the sprint ends?

**Comment by bdellasc** [comment]
The JIRA story [currently in our backlog](https://patternfly.atlassian.net/browse/RHUAP-580)

I had epics next in my list of next things to do (immediately after shutdown). I'll bring it up to to top of my list and adjust my epics stories accordingly so I can tackle it for you.

**Comment by bdellasc** [comment]
@nimishamukherjee - I got the visuals finalized and posted posted to [InVision](https://redhat.invisionapp.com/share/HJ9YNYX2T)

**Comment by nimishamukherjee** [comment]
Thanks @bdellasc

**Comment by bdellasc** [comment]
Adding links to wireframes & visuals (for future/continuing reference):
[Wireframes Flow](https://redhat.invisionapp.com/share/Y39KFTAE7)
[Visuals Flow](https://redhat.invisionapp.com/share/HJ9YNYX2T)

**Comment by michaelvirgil** [comment]
@bdellasc Looks great. One question, @Essjaysee mentioned adding a "add another" button/ability on the dialog. What is the state/status of that option?

**Comment by Essjaysee** [comment]
@bdellasc @michaelvirgil The "save and add another" button was discussed for adding tasks to a work item, which I haven't finished yet in order for Brian to add visuals to.  If we want to consider having a similar button on the creation of 'regular' work items, feel free to add a story to the backlog for us to discuss.  Thanks!

**Comment by Mgranfie** [comment]
I have a story to reevaluate our Save model, based on what happens if you
click away and re: the template. I want us to all walk through it together
and will grab some time for us on the calendar. This discussion may
influence...
