### ISSUE TITLE
Mobile Drag and Drop Interactions

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8io/fabric8-ux#68]
JIRA Story: https://patternfly.atlassian.net/browse/RHUAP-600

Almighty-Core: https://github.com/almighty/almighty-core/issues/498

--

This issue is for filling in the gaps left by the PatternFly desktop design, specifically around hover interactions and targeting.

**Comment by Essjaysee** [comment]
Is this a dupe to #81?
