### ISSUE TITLE
Label Identification Pattern

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8io/fabric8-ux#7]
As a User, I want to have the labels / tags configured with a predefined set of colors and fields.

For example, refer to https://robinpowered.com/blog/best-practice-system-for-organizing-and-tagging-github-issues/

**Comment by Mgranfie** [comment]
@mindreeper2420 we are not yet working on this... is this just an idea you are capturing?

**Comment by mindreeper2420** [comment]
@Mgranfie just capturing a request that was initial placed in the UI repo. Something to possibly look into in the future, but a backlog item for now.
