### ISSUE TITLE
FOLLOW THROUGH: Relationship links [2]

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8io/fabric8-ux#82]
RHUAP-325

**Comment by Mgranfie** [comment]
* How will a WI link be opened?
* How will it display?
* What are all the navigation points/scenarios around this?

Verification Criteria

* User can open a WIL from the WIL that is referencing it.
* User can interact with the WIL, once opened
* Navigation points and paths from an opened WIL have been determined and worked out.

**Comment by mindreeper2420** [comment]
@Mgranfie If your comment above is part of the Description, that can be edited and added to, instead of an additional comment.
