### ISSUE TITLE
WIREFRAMES: Tree Hierarchy [8]

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8io/fabric8-ux#88]
RHUAP-458

As a user of ALM I want to be able to see my stories, features, epics, in relation to one another in an iteration and in the backlog of the list view.

Establish list of requirements for support of all parent/child relationships in the tree.

Any organizational structure above iterations, will show how many levels deep and what will be order and limits of display?

Ballpark Requirements:
- Each level or branch will be displayed in the left pane. Where and how these are displayed need to be determined.
- In the list view, each level or branch should display all levels/branches below it, not including the leaves. (ie: Epics display scenarios, but not stories)
- A leaf can show a leaf, ie: a story can show a task.
- The backlog could default to showing only the leaves (stories + tasks) and we can use a filter or another mechanism to toggle the display of the tree to show the nodes up the tree, above the leaves.

Verification Criteria
* Designer reviews examples provided and explores any other examples that might provide a solution.
* Designer works to understand the criteria.
* Criteria to support the variations on the parent/child relationships have been established and approved of by stakeholders.

Example of stories with Tasks:
https://docs.google.com/document/d/1X_TOzI_uFiJ3fAlz33PwK_A91s2NRzwVudvdUC0RHoM/edit#

**Comment by deernano** [comment]
@mindreeper2420 @Mgranfie @Essjaysee 
https://redhat.invisionapp.com/share/YVA4PGYA3#/215471638_DISCOVERY

Please review the wireframes

**Comment by catrobson** [comment]
Latest wireframes are posted to InVision:  https://redhat.invisionapp.com/share/YVA4PGYA3#/216508673_Hierarchy_1_Level

@Mgranfie @mindreeper2420 @Essjaysee Please review

**Comment by catrobson** [comment]
Updated given UXD Feedback:
https://redhat.invisionapp.com/d/main#/projects/prototypes/10109165/screens

@michaelkleinhenz @michaelvirgil - Hierarchy designs are ready for development.  Could not find a story to link to.
