### ISSUE TITLE
VISUALS (SPECS): Relationship Links - Add visuals to WI details panel [5]

### ISSUE THREAD

**Issue by Essjaysee** [fabric8io/fabric8-ux#90]
Verification Requirements:
Refer to previous visual story in [JIRA](https://patternfly.atlassian.net/browse/RHUAP-594), then:

- Add specifications to previous visuals work
- Post new visual specs to InVision, review with UX team members
- Link to InVision prototypes from this story
- Tag story as "Ready for Development"

**Comment by bdellasc** [comment]
Reviewed this today, has a few more minor specs to change. Close to done, and should be done in this next round of edits.
