### ISSUE TITLE
VISUALS: Relationship Links - Add visuals to WI details panel [5]

### ISSUE THREAD

**Issue by Essjaysee** [fabric8io/fabric8-ux#94]
Originally RHUAP-320 in JIRA

Create visuals based on the following [dev issue](https://github.com/almighty/almighty-ui/pull/552) and [UXD wireframes](https://redhat.invisionapp.com/share/M28SSTLRJ)

Verification Conditions
- Create visuals mockups
- Review with UXD members
- @bdellasc can review with Sunil as his work progresses

Monica will also follow up with Konrad on the DD behavior for Link Type and the Bi-directional link for clarity of impact, if any on this story.

(Originally RHUAP-593)

**Comment by bdellasc** [comment]
I posted feedback on the flows, @sunilmalagi. A lot of the feedback is just consistency stuff.

**Comment by sunilmalagi** [comment]
Thanks Brian for your inputs,
Those changes are made and replaced the images with the same file names as you have suggested.  Please review them once again and let me know.

**Comment by bdellasc** [comment]
Had a couple of other minor comments. It's getting closer. I think you could probably wrap them up before we end the sprint tomorrow morning :-)

**Comment by bdellasc** [comment]
Just went through the last of the comments, it looks good. Specs next!
