### ISSUE TITLE
Create template for user invitation e-mail

### ISSUE THREAD

**Issue by sbryzak** [fabric8io/fabric8-ux#941]
When a user is invited to an organization or to a space, an e-mail should be sent out to the user via the notification service informing them of the invitation, and presenting them with a link to click if they accept the invitation.

This issue should be used to track the invitation e-mail template containing the layout and wording for the invitation.

See [this](https://github.com/fabric8-services/fabric8-auth/issues/507) fabric8-auth issue.

**Comment by sbryzak** [comment]
I've put together some sample templates in Google docs [here](https://docs.google.com/document/d/1ClJZ4I9Rt_3CiOe6E17C8zd_yv3oYhIqY7yiuaK8qe0/edit?usp=sharing).

**Comment by joshuawilson** [comment]
@sbryzak they are now tracking things at https://github.com/openshiftio/openshift.io/issues

**Comment by sbryzak** [comment]
Corresponding issue created: 

[https://github.com/openshiftio/openshift.io/issues/3836](https://github.com/openshiftio/openshift.io/issues/3836)

**Comment by sbryzak** [comment]
This has been implemented now.
