### ISSUE TITLE
VISUALS (SPECS): Epics [3]

### ISSUE THREAD

**Issue by Essjaysee** [fabric8io/fabric8-ux#96]
Verification Requirements:
Refer to previous visual story: [VISUALS: Epics](https://github.com/fabric8io/fabric8-ux/issues/99), then:

- Add specifications to previous visuals work
- Post new visual specs to InVision, review with UX team members
- Link to InVision prototypes from this story
- Tag story as "Ready for Development"

(Originally RHUAP-592)

**Comment by bdellasc** [comment]
Posted updated flow with specs.
