### ISSUE TITLE
VISUALS: Epics [5]

### ISSUE THREAD

**Issue by Essjaysee** [fabric8io/fabric8-ux#99]
Verification Conditions:
* Reference [wireframes](https://redhat.invisionapp.com/share/QU9U8D8GF)
* Reach out to @essjaysee to walk through/clarify any interaction specific to epics
* Complete a first pass of visuals to the related wireframe flows
* Post work to InVision

(Originally RHUAP-591)

**Comment by bdellasc** [comment]
@Essjaysee - I finished up the visuals for this flow. Next story will be spec'ing the visuals for dev, although there is a lot of overlap with Iterations and other previous work

**Comment by bdellasc** [comment]
Completed visuals, will add specs in next story

[Epics Wireframes Flow](https://redhat.invisionapp.com/share/QU9U8D8GF)
[Epics Visuals Flow](https://redhat.invisionapp.com/share/HDA61HNTA
